### ISSUE TITLE
Accessing the native contact object after adding a new contact

### ISSUE THREAD

**Issue by samerbuna** [morenoh149/react-native-contacts#105]
Would it be possible for the addContact method's callback to expose the native "id" of the added contact?

**Comment by morenoh149** [comment]
It already does as `recordId`.

**Comment by samerbuna** [comment]
@morenoh149 where?

```Contacts.addContact(newPerson, (err) => { /*...*/ })```

I've tried the callback arguments, they were undefined.

**Comment by morenoh149** [comment]
wait you'd like to tell the OS to store a new contact with an Id you provide? I don't think the underlying apis allow for this.

**Comment by pstieger** [comment]
How can i access the recordID of the last added Contact?

**Comment by npomfret** [comment]
This isn't currently possible.  We're considering returning the contact (with its id) when a contact is added.  Would that help?
