### ISSUE TITLE
Return the contact after addContact

### ISSUE THREAD

**Issue by suryaiiit** [morenoh149/react-native-contacts#107]
I think it would be better if we return the newly added contact while using addContact!!

Thanks.

**Comment by morenoh149** [comment]
Agreed, the api could be changed to
```
Contacts.addContact(newPerson, (err, createdPerson) => { /*...*/ })
```

**Comment by bietkul** [comment]
Works for IOS but it doesn't work with android.

**Comment by npomfret** [comment]
Ah yes, I don't thinks that's a documented feature - (which needs adding to android)

**Comment by bietkul** [comment]
It'll be very helpful if you can return the same because some times we need to save recordId to further update the record
