### ISSUE TITLE
Enhancement idea: stream contacts back instead of returning an array

### ISSUE THREAD

**Issue by npomfret** [morenoh149/react-native-contacts#133]
I've noticed that some people using my app have very large address books with thousands of contacts.  I think its people who have work phones and have their entire company address book synced with the phone.  It's seem surprising common place.

Maybe streaming the contacts back one by one, rather that collecting them up in an array and returning the array might be a better interface.

**Comment by morenoh149** [comment]
Fetching a subset of a user's contacts (by column or row) is actually how the underlying apis work for both platforms. Originally this module provided an abstraction over this behavior by providing the user-space program all the contacts in memory.

If however the majority of RN apps on the majority of phones trip up on this abstraction then we must provide an alternative method. One that is less expensive upfront and can operate on low RAM devices.

The question is: do we deprecate `getAll` or continue supporting it?
We should definitely offer a streaming option. 👍

**Comment by rt2zz** [comment]
agree 100% this is one of the reasons I kept the name `getAll` instead of `get`, with the idea that `get` would eventually by the primary api and perhaps we could even deprecate getAll.

Anyone have any reference examples for streaming apis in react-native? We could do basic paging, but I am hoping there is a better stream like implementation.

**Comment by Proberts** [comment]
Would returning an array of contactID's and the RN app get contacts one at a time solve this issue?  I need to add a field filter to getAll for my app. It would be trivial to getAll just the contactId's.

**Comment by npomfret** [comment]
That's not what I have in mind as the performance would be poor, you'd have to have a db query for each record plus one to get the ids.

I was thinking to simply invoke the callback once for each record, rather than invoking it with an array at the end.

**Comment by Proberts** [comment]
What sort of times are you seeing for contact db queries on devices when there are 100s of or 1000 contacts?

**Comment by npomfret** [comment]
@morenoh149 what happened to the example app project you created?  I can't find it for some reason.

**Comment by morenoh149** [comment]
@npomfret https://github.com/morenoh149/react-native-contacts-test
