### ISSUE TITLE
Bug: thumbnailPath on iOS is always showing old thumbnail even if thumbnail is changed

### ISSUE THREAD

**Issue by jln-dk** [morenoh149/react-native-contacts#169]
## Current behaviour:

On iOS, if you change the thumbnail/photo of contact from one thumbnail to another, and then use the function `getAll` the thumbnailPath will not change to the new thumbnail. Likewise if you remove the thumbnail of contact and use `getAll` the thumbnailPath will still show the old thumbnail.

## Steps to reproduce:

On iOS: 
1. Create a new contact without a thumbnail/photo (by using the Contacts app in iOS)
2. Use `getAll` to verify that thumbnailPath is empty on the new contact
3. Go to the contact again and add a thumbnail. Verify `getAll` will now show the thumbnailPath
4. Change contact thumbnail to another photo. Verify `getAll` will now NOT show the new thumbnailPath.
5. Remove contact thumbnail. Verify `getAll` will now NOT show an empty string in thumbnailPath, but still show the old thumbnail.

## Expected behaviour:

I expected the thumbnailPath to always match the latest data on the contact (e.g. updated thumbnail, removed thumbnail). On Android it works as I expect.

## Information:

Version: 0.8.1
Platform: iOS
Worked before: I can't confirm

**Comment by npomfret** [comment]
I was wondering when this would be noticed.  

The thumbnails are stored as files in the caches dir, and once written, aren't overwritten (unless the OS deletes them).  The reason for this was to improve performance.  Creating the thumbnails is incredibly slow, and for those address books that have thousands of contacts it just wasn't feasible to recreate the contact thumbnail each time.

So, I have though about some ideas that might work around the problem while keeping the performance as is.

1. Add a method to _"refresh"_ the thumbnails (asynchronously so as not to block the ui)
2. Add option to `getAll` to force recreation of thumbnails (which would be slow)
3. Add option to `getPhotoForId` to force recreation of thumbnails (which would be slow)
4. Detect when contacts are changed and regenerate the thumbnail in demand (actually no idea if this is possible)

...any other ideas?

**Comment by jesperlndk** [comment]
Hey @npomfret 

That is some very good ideas. My thoughts are:

- IMO if any function is just a bit "heavy" we should switch to an async approach / Promise-based in JS. Just so we can avoid the UI being blocked. This includes `getAll`.
- A `refresh` method might be good, but then again - how would I know when to use it? I can't get a clue if the user has changed any thumbnails. A "force: true" to `getAll` to ensure all data is new might be better a way.
- To your point 4: If we somehow very easily (read: non-heavy-action) could get some kind of hash of the contacts data, and then being able to compare if the data has changed, that would be good. Then one would be able to identify if a `getAll` with "force: true" is needed.

What do you think?

**Comment by jesperlndk** [comment]
@npomfret any update?

**Comment by npomfret** [comment]
Not yet, sorry.  I think adding a `forceRecreateThumbnails` option to the 2 methods might be the best way to go for now.  The UI shouldn't get blocked, as long as the work is done on the correct thread.  My worry was that it's just very very slow. But having the option I guess would allow the developer to make they own choice.  I guess we just need to be clear in the docs that it can be slow when the address book is large.  And the default behaviour should be not to force recreation.

There is of course a workaround already.  You could just delete the image files - the thumbnails will be created if they aren't there.  Using something like react-native-fetch-blob to access the file system and delete them is pretty easy.

Thoughts?

**Comment by kidken285** [comment]
I think this is maybe solution for me: 
-(NSString *) getFilePathForThumbnailImage:(CNContact*) contact recordID:(NSString*) recordID
{
    NSString *filepath = [self thumbnailFilePath:recordID];

//    if([[NSFileManager defaultManager] fileExistsAtPath:filepath]) {
//        return filepath;
//    }

    if (contact.imageDataAvailable){
        NSData *contactImageData = contact.thumbnailImageData;

        BOOL success = [[NSFileManager defaultManager] createFileAtPath:filepath contents:contactImageData attributes:nil];

        if (!success) {
            NSLog(@"Unable to copy image");
            return @"";
        }

        return filepath;
    }

    return @"";
}

**Comment by Akyna** [comment]
@jesperlndk any update?

**Comment by jesperlndk** [comment]
Nope
tir. 18. dec. 2018 kl. 11.08 skrev Andrii <notifications@github.com>:
