### ISSUE TITLE
Use await to get contacts

### ISSUE THREAD

**Issue by pickhardt** [morenoh149/react-native-contacts#17]
I've been looking through the code but can't figure out a good way to use await with Contacts.getAll. I want to be able to do something similar to what React Native uses for AsyncStorage (https://facebook.github.io/react-native/docs/asyncstorage.html#content)

E.g. code like this

``` javascript
  var contacts = await Contacts.getAll((err, contacts) => {
    if(err && err.type === 'permissionDenied') {
      console.log("Permission denied contacts");
      return [];
    } else {
      return contacts;
    }
  });

  for (var i = 0; i < contacts.length; i++) {
    var contact = contacts[i];
    // do stuff here
  }
```

Do you have any ideas on how to do this or would it require some changes to the project code? I think it isn't supported currently.

**Comment by morenoh149** [comment]
are you putting that code within a function declared as `async`?

also async/await only works for functions that return `Promise`s. See https://www.twilio.com/blog/2015/10/asyncawait-the-hero-javascript-deserved.html

**Comment by rt2zz** [comment]
@pickhardt I believe promise and by extension async/await can be added fairly easily: https://medium.com/the-exponent-log/react-native-meets-async-functions-3e6f81111173#.odjz3awk0 although I have not looked into what it might take to preserve compatibility with callbacks.

PR's accepted

**Comment by morenoh149** [comment]
@rt2zz that blog post suggests that RN modules should use `async` moving forward. But the callback style works just fine for me.

**Comment by tomauty** [comment]
Would love promise support, as that's how I'm using async actions in my app :)

**Comment by tomauty** [comment]
Will attempt a PR soon

**Comment by tomauty** [comment]
Sorry for double post, I'm on my phone. Would you accept a PR that doesn't allow callback compatibility?

**Comment by morenoh149** [comment]
Pretty sure async/await aka promise support would just require another api endpoint (as far as the android api is concerned). In java we support [method overloading](http://docs.oracle.com/javase/tutorial/java/javaOO/methods.html) and we could simply declare another [getAll()](https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L36) that is invoked without a callback. This version would instead accept and resolve a promise. See [native modules android #promises](https://facebook.github.io/react-native/docs/native-modules-android.html#promises)


ping @rt2zz

**Comment by rt2zz** [comment]
@morenoh149 I think we could alternatively promisify the callbacks in the js code and *always* return a promise in addition to triggering the callback if present.

**Comment by sibeliusseraphini** [comment]
Promisify of `Contacts.getAll` using js
```js
function getContacts() {
  return new Promise((resolve, reject) => {
    Contacts.getAll((err, contacts) => {
      if (err) {
        reject(err);
      } else {
        resolve(contacts);
      }
    });
  });
}
```

**Comment by morenoh149** [comment]
I'll add this soon https://facebook.github.io/react-native/docs/native-modules-ios#promises seems straightforward.

**Comment by utkarsh-dixit** [comment]
I'd like to takeup this issue.

**Comment by morenoh149** [comment]
@utkarash-dixit go for it. Should be easy

**Comment by Bilal-Abdeen** [comment]
To use this great component with Redux, I needed to make it return promises (rather than callbacks). Using the hints in this thread and other resources, I came up with a solution for calling this component from a Redux's Action (Action Creator).

Please, refer to the following question on StackOverflow.
https://stackoverflow.com/questions/58126240/in-a-reduxs-action-calling-a-function-with-callbacks

**Comment by zingerj** [comment]
Hey @utkarsh-dixit, are you still working on this? If not, I'll take a crack at promisifying all of the methods. I can either add code to each one to accept a callback or be used with `async`/`await` (which I think would be easier) or I can add new methods like `getContactsAsync`. I'm leaning towards the former, but do you have a preference @morenoh149 (or anyone on this thread)?

**Comment by morenoh149** [comment]
@zingerj please feel free to take this over. In oss things tend to be dropped.

I have no preference on implementation (I think). So lets go with your preference.

**Comment by hengkx** [comment]
any progress?

**Comment by morenoh149** [comment]
no progress. Please submit a PR.
