### ISSUE TITLE
wrong name on android

### ISSUE THREAD

**Issue by lyudad** [morenoh149/react-native-contacts#173]
often names are duplicated and if look at phone numbers one is right,  one is not. (start some weeks ago)
Example:
in phonebook - lyuda +380965556655
                        amy   +380950009900

Contacts.getAll function -  lyuda +380965556655
                                         lyuda  +380950009900

**Comment by npomfret** [comment]
Thanks for this.  Is this a bug on iOS or Android or both?

Just to be clear from your example - you are getting one contact name with the phone number of another contact? And a contact has been duplicated?

You are using the latest release from npm?

**Comment by lyudad** [comment]
![img_3348](https://cloud.githubusercontent.com/assets/25103090/25421956/cdb6691a-2a67-11e7-868f-8f7b62eca185.JPG) 
I know for sure that it happend in Android (4.4.2, 5, 6, 7) and  Iphone 7 (screenshot). it can't be 3 same name, only 2 and if look to the phones behind the name, one number is right, but other need have other name (right phone number can be first or second)

- yes -  I'm getting one contact name with the phone number of another contact
- yes - I have latest release from npm

**Comment by npomfret** [comment]
If you console.log the output of `getAll` can you see the errors in the data?

**Comment by lyudad** [comment]
Contacts.getAll((err, contacts) => {
        console.log('contacts', contacts)
})

yes error start from there, that's why I wrote here (first I thought that I done something wrong)

**Comment by npomfret** [comment]
Can you paste a snippet of some wrong information? (change the data if you don't want to paste real contact information here)

**Comment by lyudad** [comment]
![screenshot from 2017-04-26 14-35-25](https://cloud.githubusercontent.com/assets/25103090/25432624/da2e7630-2a8d-11e7-8b3c-b78aa135ede7.png) - right phone number and name
![screenshot from 2017-04-26 14-35-13](https://cloud.githubusercontent.com/assets/25103090/25432638/eea18ae4-2a8d-11e7-8ea9-6538b1ad47ee.png) - wrong name (right - "велосипед")

**Comment by lyudad** [comment]
it is not only with Russian names, also if names in English or French (do not check other)

**Comment by lyudad** [comment]
I can give link for app, if it can help

**Comment by sneerin** [comment]
it might be related to some viber or whatsapp contacts....
