### ISSUE TITLE
ios region is city, should be state

### ISSUE THREAD

**Issue by johnwnowlin** [morenoh149/react-native-contacts#185]
Contacts from IOS return the city in the region property. Should be returning state/region in the region property.

RCTContacts.m line 193 should be 
        `NSString* region = postalAddress.state;` 
instead of 
        `NSString* region = postalAddress.city;`

**Comment by nikhilcoolstuff** [comment]
+1 I'm experiencing the same issue. Thanks for the temp solution John!
