### ISSUE TITLE
getAll return not all contacts

### ISSUE THREAD

**Issue by klinkov** [morenoh149/react-native-contacts#207]
Hi

I have on my iPhone  227 contacts total. But getAll return only 220 contacts. Any idea what is wrong?

ios 10.3.3

**Comment by soutot** [comment]
I was able to return more than 3 thousand contacts at once, so I think there isn't any kind of limitation in the lib.

Do you know which contacts exactly aren't being returned?

I would first check if there's any difference between them and the others, like special characters. Let me know if you find anything

**Comment by klinkov** [comment]
I have several contacts sources (Gmail, Exchange, iCloud). Could this causing the problem?

**Comment by morenoh149** [comment]
Needs more info about the phone and code. Share an emulator image and a example app via GitHub repo.
