### ISSUE TITLE
thumbnailPath on android is not accessible - content://com.android.contacts/contacts/4/photo

### ISSUE THREAD

**Issue by EyalSi** [morenoh149/react-native-contacts#223]
I'm trying to copy the thumbnail received on Android, using RNFS (react-native-fs)
copyFile(src, dst) or RNFetchBlob (react-native-fetch-blob) fs.cp(src, dst), doesn't succeed - "no such file or directory".
Anyone had a success in copying such `content://` files?
Thanks,

**Comment by EyalSi** [comment]
Is nobody using the thumbnails on android?

**Comment by morenoh149** [comment]
do you know if where you're using the uri has the same contentresolver authority? https://developer.android.com/reference/android/content/ContentUris.html Maybe the authority is `com.android.contacts` and then your module is using a different authority?

**Comment by EyalSi** [comment]
@morenoh149 how do I set the authority? I'm using react-native-contacts and than trying to read the image using RNFS. I'm not setting the authority in either...

**Comment by morenoh149** [comment]
Right those may be two different authorities. Basically the uri 's generated by different authorities are not compatible. Don't think you can achieve your goal with that approach.

**Comment by EyalSi** [comment]
There is now a solution for this problem in react-native-fs. Enabling access and copy content:// files -https://github.com/itinance/react-native-fs/pull/395

**Comment by morenoh149** [comment]
Is your issue resolved?

**Comment by JeanPSF** [comment]
Updates? I am with the same problem.

**Comment by morenoh149** [comment]
No updates. Did you try passing the authority between the libraries? For better help open a fresh issue referencing this and any other resources. Also include a minimal reproduction and what you tried.
