### ISSUE TITLE
Add pagination to avoid memory exception

### ISSUE THREAD

**Issue by sunnynegi** [morenoh149/react-native-contacts#226]
Hi there need help over fetching contact from phone, When i try to get contacts from my phone to my app its taking too much time because of large number of contacts in my phone.

Here is code that i am using
```js
importFromContacts() {
   Contacts.getAll((err, contacts) => {
      if(err === 'denied'){
        // error
      } else {
        this.setState({
          contactList: contacts
        })
      }
    })
  }
```
is there any alternative way to fetch only 10 and when user scrolled down then I send one more request to get more contacts

**Comment by morenoh149** [comment]
Pagination. Good idea.

**Comment by nightraiser** [comment]
Is there a way to get only limited number contacts for a time and updating the offset and requesting for the second page ?

**Comment by morenoh149** [comment]
@nightraiser not yet. We need to implement pagination and native side filtering.

**Comment by iagorm** [comment]
There would be good to have something like, number of contacts per page, then you get all the list length and divides per number of contacts per page, then you have the numbers of pages, but this would take a time at first because of first iteration in java side.

**Comment by CodeXpertsDev** [comment]
@morenoh149 Is this under development? Any ETA on the implementation?

**Comment by morenoh149** [comment]
@CodeXpertsDev not under development. Feel free to implement.
