### ISSUE TITLE
Android won't update contact array fields (email, phone) if none exist

### ISSUE THREAD

**Issue by paintedbicycle** [morenoh149/react-native-contacts#270]
If I have a contact that exists, but they do not have any email addresses, calling "updateContact" and passing the new email address will not save on Android.

However, if I already have one or more email addresses, I can successfully update that email or add a new email to that array.

This does not affect iOS.

Android should allow insertion of new objects to the empty arrays.

**Comment by mohsinriaz17** [comment]
> If I have a contact that exists, but they do not have any email addresses, calling "updateContact" and passing the new email address will not save on Android.
> 
> However, if I already have one or more email addresses, I can successfully update that email or add a new email to that array.
> 
> This does not affect iOS.
> 
> Android should allow insertion of new objects to the empty arrays.

any update on this, ?? or any one can guide me where to start looking for a fix in android native module files ?

**Comment by morenoh149** [comment]
@mohsinriaz17 somewhere in this function regarding urlAddresses https://github.com/rt2zz/react-native-contacts/blob/464a14d9a1d6f95d23f8f610359dee3eccbe4d05/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L178

OR in the same function regarding emailAddresses https://github.com/rt2zz/react-native-contacts/blob/464a14d9a1d6f95d23f8f610359dee3eccbe4d05/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L189

PRs welcome
