### ISSUE TITLE
Feature request: Callback when openContactForm when creation screen is closed

### ISSUE THREAD

**Issue by nous-** [morenoh149/react-native-contacts#276]
Modify `openContactForm(openCallback)` to know when creation screen is closed, along with contact if created.

Adjust function to `onContactForm([openCallback, completionCallback])` where `openCallback(error)` and `completionCallback(err, contact)`. Error and contact can both be null in the case where the user cancelled.

**Comment by Fernand30** [comment]
You are right. But I can't find yet

**Comment by morenoh149** [comment]
the contact creation event is already requested https://github.com/rt2zz/react-native-contacts/issues/57
