### ISSUE TITLE
Docs: Using it with Pod 

### ISSUE THREAD

**Issue by GeekRishabh** [morenoh149/react-native-contacts#278]
How to use this package when we are using Cocoapods. I am also using [react-native-firebase](https://github.com/invertase/react-native-firebase)  . Please provide docs how to use it. 
Sharing My Podfile
```
platform :ios, '8.0'

target 'test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

 # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'
end
```
Have upgrade to `platform :ios, '9.0'` but this breaks the firebase linking modules

**Comment by morenoh149** [comment]
I don't use podfiles, perhaps borrow inspiration from https://github.com/msand/SVGPodTest/blob/master/ios/Podfile#L12
