### ISSUE TITLE
UpdateContact Method is updating all numbers in the contact instead of a specific number

### ISSUE THREAD

**Issue by selvanr211** [morenoh149/react-native-contacts#287]
Working on an app where we need to change the prefix of numbers from XXX to YYY. 

The contact list is well populated and all is working fine. However, updating 1 specific number for a Contact is not working well. UpdateContact is updating all the numbers for this Contact with the new number. 

We are able to get the list of contacts found in the contact book via this code:

 ```
//phoneContacts => all the contacts found in the address book
 //contactDetails => all the contacts that have the prefix number that needs to be replaced. 
 //prefixNumber => is the prefix number that user wants to replace.
 handleUpdate = () => {
 const { phoneContacts, contactDetails, prefixNumber } = this.state;
 var updated_select = 0;
 var record = null;

  Contacts.getAll( (err, contacts) => {

  _.forEach(contactDetails, (contactD) => {

    if (contactD[1] == true) {

      //where contactD[5] is the specific phone number
       var num = contactD[5];
       num = num.replace(prefixNumber, '010');

      _.forEach(contacts, (cont) => {
         if (cont.recordID === contactD[0])
            //finding the record to be updated in the Contact List
            record = cont;
       });

       //Replacing the record phone numbers with the updated one. 
       record.phoneNumbers[contactD[3]] = { label: contactD[4], number: num };

       //Updating the contacts as per the guide linked above
       //when we verify the values of record, it contains the correct values. That is, it has the number that has been updated as well as the other numbers for this contact. 
       Contacts.updateContact(record, (err) => {
         if (err) {
           _alert('error', 'Application error: Update unsuccessful.');
           return;
         }
       });
        ++updated_select;
       }

  });

  ToastAndroid.show(updated_select + ' rows have been updated', ToastAndroid.SHORT);
   this.handleSearchContacts();
   return;
 });
}
```
So as a concrete example. We are changing the prefix number from 555 to 010 If User X has

```
phoneNumbers: [
   {label: "work",number: "(555) 555-5555"},
   {label: "mobile",number: "(444) 444-4444"},
  ],
```
On update, the app is updating both numbers for User X to:

 ```
phoneNumbers: [
       {label: "work",number: "(010) 555-5555"},
       {label: "work",number: "(010) 555-5555"},
      ],
```
During debugging, we verified the value of variable record and it is showing the contact with the all its details long with the specific phone number updated correctly.

Any ideas?

**Comment by morenoh149** [comment]
sounds like a bug and something we've never tested. Are you seeing this behavior on both platforms?

**Comment by selvanr211** [comment]
@morenoh149 Didn't test on both platforms. This was done on Android. Will try on iOS and update.

**Comment by morenoh149** [comment]
@selvanr211 nope, I have higher priority issues to address and limited time (only some weekends) to work on this. PRs welcome.

**Comment by AnkitKaneri** [comment]
@morenoh149 Can you verify #296 PR. @selvanr211 I think this code is going to work in your case if you are still finding the solution you can give this a try :) .

**Comment by selvanr211** [comment]
@AnkitKaneri  thanks! We actually did a native app in Android for our need. iOS Version was working anyway. Will give the update a try and let you know.
