### ISSUE TITLE
openContactForm familyName and givenName does not work

### ISSUE THREAD

**Issue by AndrewSheetMetal** [morenoh149/react-native-contacts#302]
Hi everyone,

I'm currently testing react-native-contacts with Android (7.0) and try to use the openContactForm() method. It works perfectly (Thanks!) except for the familyName and givenName :(
They are not displayed in the contacts app.
I also tried to use "firstName" and "lastName" but they also didn't worked.

Best regards
Andreas

**Comment by morenoh149** [comment]
See https://github.com/rt2zz/react-native-contacts#example-contact-record
> on Android versions below 8 the entire display name is passed in the givenName field. middleName and familyName will be ""
Please doublecheck you are coding against these assumptions.

If you still have a problem please share your exact code snippet and any adb logs.

Relevant source region https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L225

**Comment by varun-brainizen** [comment]
I am facing the same Issue, My code - 
contact object -
let addContact = {
                familyName: "Makhija",
                givenName: "Varun",

                phoneNumbers: [{
                    label: "mobile",
                    number: "1234567890"
                }],
            }
code to show contact form - 
addContact(addContact){
    

Contacts.openContactForm(addContact, (err) => {
        if (err) console.log(err);
       
      })
}

**Comment by morenoh149** [comment]
on android versions below 8 you have to use `displayName` see https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L268

**Comment by schumi1331** [comment]
I think this is a general Android bug isn't it? At least it is not working for me with Android 8.1 as well, other fields works without any problem.

I found one error in ContactsManager.java at line 223:
`name.put(ContactsContract.Contacts.Data.MIMETYPE, ContactsContract.CommonDataKinds.Identity.CONTENT_ITEM_TYPE);`

I guess this should be `ContactsContract.CommonDataKinds.StructuredName.CONTENT_ITEM_TYPE`. But it was not working for me with that as well.

**Comment by dmitrizagidulin** [comment]
+1, also running into this issue.

**Comment by ddxxtony** [comment]
the same problem, someone has found a solution ?

**Comment by codevoler** [comment]
check language's device, pls

**Comment by sergchernata** [comment]
Only `displayName` worked, android version `10`.
