### ISSUE TITLE
Refresh App State after closing contact form

### ISSUE THREAD

**Issue by theoryweary** [morenoh149/react-native-contacts#308]
After calling ```  Contacts.openContactForm({}, (err) => {
      if (err) throw err;
      // form is open
    })```, and adding a contact, the app is called but I don't know how to re-render the app to actually show the new contact.  I tried using the React-Native lifecycle methods, but on iOS it seems like the app never technically leaves the foreground even while the AddContactForm is open.

Can you add something to the openContactForm function to be called when the contact is successfully added?

**Comment by GagarinAP** [comment]
actual!!!

**Comment by morenoh149** [comment]
if you could review this PR I think it adds support for detecting changed contacts https://github.com/rt2zz/react-native-contacts/pull/184/files

**Comment by omarchacinortega13** [comment]
Facing the same issue - COuld we review this PR?

**Comment by morenoh149** [comment]
@omarchacinortega13 could you rebase the PR and test it?

**Comment by lonnylot** [comment]
@morenoh149 #184 seems to be closed instead of merged. Is there another PR that adds the `subscribeToUpdates` method that we can test/merge?

**Comment by morenoh149** [comment]
@lonnylot #184 title said the pr was for the permission system. there is a method `subscribeToUpdates` but it was not described and so it was not merged. If you need it please open a new pr for why and copy paste the right parts of the pr.

**Comment by Jalson1982** [comment]
Any update on this? This would be really great feature!

**Comment by morenoh149** [comment]
@Jalson1982 did you read
> @lonnylot #184 title said the pr was for the permission system. there is a method subscribeToUpdates but it was not described and so it was not merged. If you need it please open a new pr for why and copy paste the right parts of the pr.

do you want to give it a shot?
