### ISSUE TITLE
android permission

### ISSUE THREAD

**Issue by qq912276337** [morenoh149/react-native-contacts#309]
some devices refused permission by user, PermissionsAndroid.request always return 'granted'.in fact ,it is denied.

**Comment by jmfirth** [comment]
This issue was reported in an application I am working on as well.  On Android, whether the permission was granted or not, it always comes back as `PermissionsAndroid.RESULTS.GRANTED`.

react-native-contacts@2.2.0

**Comment by morenoh149** [comment]
@jmfirth not sure either, maybe resolve the conflicts and try out the PR
