### ISSUE TITLE
IOS>No data retried after second launch

### ISSUE THREAD

**Issue by shemilhashan** [morenoh149/react-native-contacts#321]
Tested in
ios: 11.4
model: iphone 7 plus
rn version: 0.50.4

I have added the contact permission. 

First launch of app:
In the specific page where contact list is required, permission pop up does not appear. Once back is pressed, permission pop up appears and allow. Then go back to contacts list page, it shows contact data.

Second launch:
close the app, terminate it, run again.
Go to contacts list view, returns empty, no contacts shown.

Why is this happening?

**Comment by morenoh149** [comment]
Can you double check you installed the library correctly. Share your code.
