### ISSUE TITLE
Update contacts on android not updating contact information, delete contact on android not working

### ISSUE THREAD

**Issue by newseedit** [morenoh149/react-native-contacts#358]
There seems to be an issue with updating contact information and deleting a contact on Android. updateContact updates all information(Phone numbers, email addresses etc), except the fields givenName, middleName, familyName, prefix, suffix, company, jobTitle and department.

We are getting no errors, and it is returning a contact in the callback.

Delete is also going through without any errors, but the contact is not deleted.

We encountered this issue when updating from version 2.1.5 to version 3.1.2. 
We've also tested on a barebone react native project this using the following code (this is just testing update contact)

```export default class App extends Component<Props> {
  render() {
    Contacts.getAllWithoutPhotos((err, abContacts) => {
        console.log(abContacts);
        abContacts[0].givenName = "asd";
        abContacts[0].familyName = "asd";
        abContacts[0].company = "asd";
        abContacts[0].prefix = "asd";
        abContacts[0].suffix = "asd";
        abContacts[0].jobTitle = "asd";
        abContacts[0].department = "asd";
        abContacts[0].note = "asd";
        abContacts[0].postalAddresses[0].state = "asddsa";
        abContacts[0].postalAddresses[0].region = "asdsa";
        Contacts.updateContact(abContacts[0], (err) => {
        });
    })
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Welcome to React Native!</Text>
        <Text style={styles.instructions}>To get started, edit App.js</Text>
        <Text style={styles.instructions}>{instructions}</Text>
      </View>
    );
  }
    async componentWillMount() {
        await requestReadContactsPermission();
        await requestWriteContactsPermission();
    }
}
```

We've also tested react-native-contacts-test with the same result.

Tested version: 3.1.1, 3.1.2
RN version: 0.56, 0.58
Tested on Samsung Note 3 android 5.0, Google Nexus 5 android 6.0.1 and Google Pixel android 8.1.0

**Comment by morenoh149** [comment]
Please perform a bisect and determine the first version that causes the issue. There have been 6 releases between 2.1.5 and 3.1.2

**Comment by newseedit** [comment]
Tested now on RN 0.58.3
Versions tested 3.1.2, 3.1.1, 3.1.0, 3.0.2, 3.0.1, 3.0.0 and 2.2.5.
Android version 6.0.1

2.2.5 was the latest release where both delete and update is working for us, neither update nor delete works on later releases.

**Comment by newseedit** [comment]
I've added a PR #363 solving this issue. The problem was that contactId was set to rawContactID before being returned to the user, even though those values might differ if the user has had any changes made to it. I don't know if this reintroduces any bugs with duplicate contacts.

**Comment by morenoh149** [comment]
yeah, it seems like using the rawContactID and using the contactId both have pitfalls.

**Comment by newseedit** [comment]
I created a new PR #367 where contacts are being mapped based on contactId (just like pre 3.0.0). Now update and delete is working, and getAll() is no longer returning duplicate contacts.
