### ISSUE TITLE
Open ios/android default contacts app by pressing a button

### ISSUE THREAD

**Issue by abdulbasit1248** [morenoh149/react-native-contacts#360]
by using this package we can access all contacts in the form of array . how to open device's default contacts app .by pressing the button

**Comment by morenoh149** [comment]
have you seen openContactForm and openExistingContact?

**Comment by abdulbasit1248** [comment]
![contact_add_contacts](https://user-images.githubusercontent.com/43878789/52327405-d2239700-2a0d-11e9-9922-f4eec0919b09.jpg)

I am talking about this screen . how to get this screen open when user clicks on button "select contact" openContactForm is taking me to the editable contact screen .can you please elaborate ?

**Comment by morenoh149** [comment]
no function like that. Would you simply launch the phone's contacts application? I think there is another way to achieve this.

**Comment by abdulbasit1248** [comment]
Nothing available for that .accept one package "React-native-contact-wrapper" which has bugs and issues with minimum api level version in android platform .
Is it possible for you people to add this functionality in this package? @morenoh149

**Comment by kenkotch** [comment]
look at react-native's Linking api
https://facebook.github.io/react-native/docs/linking

**Comment by thanhluantl2304** [comment]
any update on this? I really need this

**Comment by morenoh149** [comment]
@thanhluantl2304 no update.

**Comment by skruegs** [comment]
@abdulbasit1248 @thanhluantl2304 Any chance you found a way to do this?
