### ISSUE TITLE
GetAll in android is displaying duplicate contacts even if contact is not duplicated in phone

### ISSUE THREAD

**Issue by kottamasusaikumar** [morenoh149/react-native-contacts#361]
GetAll in android is displaying duplicate contacts even if contact is not duplicated in phone

**Comment by muhammadwfa** [comment]
**// first declare a var withing class.
_mcontacts=[];**

**// then add the following statement to populate the _mcontacts and remove the spaces
// also it will take just first index, it means _mcontacts wont be duplicate.**
```
componentDidMount(){
   Contacts.getAll((err, contacts) => {
          if (err === 'denied') {
            console.log("Errorrrrrrrr: " + err);
          } else {
                contacts.forEach(item => {
                    if (!(!Array.isArray(item.phoneNumbers) || !item.phoneNumbers.length)) {
                       this._mcontacts.push({ number: item.phoneNumbers[0].number.toString().replace(/\s/g, 
                       ''),  name: item.givenName });
                    }
                 });
          }
    }
}
```

**Comment by kottamasusaikumar** [comment]
I hope you are checking the length of the phone numbers and checking whether the phone numbers is an array or not and the duplicates are not removing and that too you are considering only a single phone number for an user and missing multiple numbers for a contact (phoneNumbers[0]). It is not the solution to the problem. I appreciate for your reply.

**Comment by morenoh149** [comment]
What platforms are you observing this on? How would you describe a duplicate contact?

It's likely that the module is returning several records (likely on android) that the native contacts app consolidates into a single contact. On android, anecdotally, I've seen one "contact" returned programmatically as several. You may see one version from WhatsApp, one from adding in the address book and another via gmail or some such. The native address book tends to consolidate these.

**Comment by kottamasusaikumar** [comment]
okay thank you, can we know the country code based on the phone number(contacts["phoneNumbers"][0]["number"] gives phone number)

**Comment by morenoh149** [comment]
@kottamasusaikumar please ask programming questions on stackoverflow

**Comment by yianyue** [comment]
I ran into the same issue on an Android 9 device

In my case, any contact with linked whatsapp account ends up with multiple entries of the same phone number. The phone number array would look something like this:
```
[ { id: '1', label: 'mobile', number: '+1 222-333-4444' },
  { id: '2', label: 'mobile', number: '+1 222-333-4444' }]
```

https://github.com/rt2zz/react-native-contacts/pull/350 fixes the duplicate number issue, but also got rid of emails for some reason...I don't know enough about android development to guess at why

**Comment by morenoh149** [comment]
yep its been wackamole with this issue, need someone to really understand the tradeoffs and communicate that in the api docs.

**Comment by Saurab-Rakshit** [comment]
How to compare "displayName" property of two different contact names in the list , so that we can find out the duplicate contact names & color it with identical colors.

**Comment by Blackbird312** [comment]
1. **Temporary solution using Set and filter(), for people having this problem :** 

```
type phoneType = {
    id: string
    fullName: string
    telephone: string
  }. //Modify the type as you see fit

  let removeDuplicatePhoneNumber = (phones: phoneType[]) : phoneType[] => {
    const uniquePhones = new Set();
    const filteredData = phones.filter((item:phoneType) => {
      const normalizedPhone = item.telephone.replace(/[-\s]/g, ''); // Remove dashes and spaces
      if (uniquePhones.has(normalizedPhone)) {
        return false; // Duplicate, so skip it
      }
      uniquePhones.add(normalizedPhone);
      return true; // Unique, so keep it
    });

    return filteredData
  }
  ```

2.   **Then, use flatMap to make the array much simpler :**

  
  ```
  let requestContactsAccess = () => {
    Platform.OS === 'android' && PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_CONTACTS, {
      title: 'Contacts',
      message: 'This app would like to view your contacts.',
      buttonPositive: 'Please accept bare mortal',
    }).then((res) => {
      console.log('Permission: ', res);
      Contacts.getAll()
        .then((contacts) => {
          let flattenedContacts = contacts.flatMap((contact: any, index: number) => (
            contact?.phoneNumbers?.map((phoneNumber: any) => ({
              id: index + '-' + phoneNumber.label,
              fullName: contact.givenName + ' ' + contact.familyName + ' (' + phoneNumber.label + ')',
              telephone: phoneNumber.number
            })) //Modify the returned object as you see fit.
          ))
          let removedDups = removeDuplicatePhoneNumber(flattenedContacts)
          setData(removedDups)
        })
        .catch((e) => {
          console.error(e);
        });
    }).catch((error) => {
      console.error('Permission error: ', error);
    })
  }
  ```
