### ISSUE TITLE
feature Request: Get AllContacts without permission READ_PROFILE

### ISSUE THREAD

**Issue by soroushm** [morenoh149/react-native-contacts#373]
For some reason our user won't to  give READ_PROFILE permission so app will be crash it was very helpful if get All contacts get all contacts minus the user contact

**Comment by morenoh149** [comment]
@soroushm do you know if it's even possible to read contacts without this permission?

**Comment by soroushm** [comment]
Yeah we are comments this permission in our version everything working fine exception in older version just owner profile contact will be missing!
