### ISSUE TITLE
Android permission for api level > 23 and < 23

### ISSUE THREAD

**Issue by Ameetest** [morenoh149/react-native-contacts#381]
![Screenshot_20190411_163954](https://user-images.githubusercontent.com/33896763/55953192-0ec37700-5c79-11e9-8f58-6e1e1fadb323.jpg)

The code to addContact in as below.
  
```es
gotoContect = () => {
      var newContact = {
                firstName: firstName,
                middleName: '',
                lastName: lastName,
                phoneNumbers: [{
                    label: 'test',
                    number: number,
                }],
                emailAddresses: [{
                    label: 'test',
                    email: email,
                }],
            }

            PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.READ_CONTACTS,
                {
                  'title': 'Contacts',
                  'message': 'This app would like to view your contacts.'
                }
              ).then(() => {
                Contacts.addContact(newContact, (err) => {
                    if (err) throw err;
                    // save successful
                    this.props.navigation.goBack()
                })    
              })
}
```

In some devices i get this permission error.
**Don't know what is going wrong??**

**Comment by morenoh149** [comment]
There are two ways to get permissions in android . Be sure to study the readme. You must build your logic to detect the api. Erwin if you want to support older apis and request the permission in both ways. Ask for more details once you try doing that.

Also you need triple backticks to do code highlighting.

**Comment by Ameetest** [comment]
@morenoh149  In app setting permission , App ask for permission ,After allowing the permission 
still addContact shows this error ,

  
![Screenshot_20190412-114849](https://user-images.githubusercontent.com/33896763/56016296-66b1ba80-5d19-11e9-876b-285f171d6399.png)

**Comment by morenoh149** [comment]
What api level? Try changing the api level above 23

**Comment by Ameetest** [comment]
Below is api level 

        minSdkVersion = 23
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"

**Comment by morenoh149** [comment]
Ok. The error is complaining about a write permission. Try requesting `android.permission.WRITE_CONTACTS` as well. See https://devdocs.io/react_native/permissionsandroid

**Comment by prashantbw** [comment]
I am having the same issue @Ameetest were you able to solve this problem
