### ISSUE TITLE
Feature Request: How do I display to the user that Contact was saved

### ISSUE THREAD

**Issue by shantang96** [morenoh149/react-native-contacts#393]
Hi,

Firstly, great package! Works like a charm. 

I'm trying to make it so that once the user opens the Contact Form and hits Done, he should be able to see the button changed to "Saved to Contacts", and if he hits Cancel it should remain as it was i.e "Add To Contacts". 

It'd be great if this was a feature of the package.

**Comment by morenoh149** [comment]
please add a screenshot of what you want

**Comment by shantang96** [comment]
<img width="267" alt="Screen Shot 2019-05-20 at 2 27 28 PM" src="https://user-images.githubusercontent.com/10554513/58046604-6b813f80-7b0b-11e9-9ac0-f210b2b0fa0d.png">

I have the above button, and I want it to change to "Saved To Contacts" when the contact is saved successfully, but how do I find out if it was?

**Comment by morenoh149** [comment]
please add a fuller screenshot, still don't get the context of your request

**Comment by shantang96** [comment]
Sure, sorry about that. Okay, so below I have the Card that has the 'Add To Contacts' button. 
<img width="316" alt="Screen Shot 2019-05-20 at 3 07 08 PM" src="https://user-images.githubusercontent.com/10554513/58048799-092b3d80-7b11-11e9-98c7-b5f6ee8deb69.png">

When it's clicked, it goes to this screen using the openContactForm( ).
<img width="308" alt="Screen Shot 2019-05-20 at 3 07 19 PM" src="https://user-images.githubusercontent.com/10554513/58048822-13e5d280-7b11-11e9-9813-2ca089806f68.png">

Now, when I click Done on the above form, I want the button on the Card to say "Contact Saved Successfully", I just want a way of knowing that it was saved successfully. 

I hope that clears it up. :)
