### ISSUE TITLE
[Android] Allow custom projection to improve performance

### ISSUE THREAD

**Issue by jmrossy** [morenoh149/react-native-contacts#396]
Thanks for the great RN lib!

It seems that the `getAll()` method always returns all fields for all contacts. This is nice and simple but gives worse performance than defining a smaller, custom projection before querying for contacts.

Can we add a param to getAll, a list of desired properties, and have the query be narrowed down to that?

**Comment by jmrossy** [comment]
Related: https://stackoverflow.com/questions/10844672/how-load-all-the-contacts-with-minimum-time-in-android

**Comment by morenoh149** [comment]
requires api change. PRs welcome.
