### ISSUE TITLE
Notes not returned on Android

### ISSUE THREAD

**Issue by hexatex** [morenoh149/react-native-contacts#406]
On IOS I am able to retrieve the notes for a contact, but that doesn't seem to be the case on android...

<img width="190" alt="Screen Shot 2019-07-12 at 8 55 11 AM" src="https://user-images.githubusercontent.com/3663835/61141707-000c7c00-a483-11e9-9c53-3a070fad62c7.png">

Is this a known issue?

**Comment by rdewolff** [comment]
I have the same issue here, I have contacts on Android with notes, but the note field is empty.
