### ISSUE TITLE
Duplicate name when only last name is provided in contact

### ISSUE THREAD

**Issue by sambegin** [morenoh149/react-native-contacts#407]
On Android 
Step to reproduce : 
- Create a contact in the contact app with a last name **only**
<img width="476" alt="Screen Shot 2019-07-12 at 12 03 13 PM" src="https://user-images.githubusercontent.com/6645382/61142218-39ea7c00-a49d-11e9-9542-eb9c78b2820b.png">

- Fetch contacts with this plugin
- Result : 
<img width="587" alt="Screen Shot 2019-07-12 at 12 02 40 PM" src="https://user-images.githubusercontent.com/6645382/61142240-45d63e00-a49d-11e9-9e83-5997eba0f0fa.png">

**Comment by morenoh149** [comment]
might be related to the edit form (update open contact form placing the previous name in the form) https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L397

PRs welcome

**Comment by codevoler** [comment]
Hi, it's relate languge's device. You can check it.
