### ISSUE TITLE
openContactForm is not working on IOS device. does nothing.

### ISSUE THREAD

**Issue by abhi-nahi** [morenoh149/react-native-contacts#408]
Not sure, but what documentation says that openContactForm will open add contact UI of native before saving it to the local device which is not working on IOS device.
![Screenshot 2019-07-16 at 11 33 53 AM](https://user-images.githubusercontent.com/46667202/61270004-f013d580-a7bd-11e9-91ca-77c5a4501d43.png)

_Originally posted by @abhi-nahi in https://github.com/rt2zz/react-native-contacts/issues/368#issuecomment-511678757_

**Comment by abhi-nahi** [comment]
@rt2zz  Hello there, Can you please help me in opening the "Add new contact UI" for ios device.

**Comment by danielidt** [comment]
@abhi-nahi latest master is working for me on IOS. Make sure you've provided contacts permissions to your app

**Comment by abhi-nahi** [comment]
> @abhi-nahi latest master is working for me on IOS. Make sure you've provided contacts permissions to your app

Yes, I have. This is the single method not responding on ios platform. Rest all the functions are working fine.

**Comment by pasihu** [comment]
I have the same problem. I don't get any error or anything. I only tried to use the method on simulator so far but i don't think that is the problem. addContact and checkPermission methods works fine.

**Comment by morenoh149** [comment]
@divityodaplus looks like there's a patch at https://github.com/robertwood-mobile/React-Native-Contacts/commit/65bf6e8480d48b0c2f697a553adf50b6ad4116b2 could you submit this as a pr
