### ISSUE TITLE
iOs 7.0 deployment target no longer supported

### ISSUE THREAD

**Issue by wichert** [morenoh149/react-native-contacts#409]
With a XCode 10.2 setup we can no longer use this package:

```
The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.2.99. (in target 'RCTContacts')
```

Can you bump the deployment target to 9.0? That will still support all iOs hardware from 2011 on, and should keep us happy for another 1.5 years or so.

**Comment by morenoh149** [comment]
yeah I think this commit can be reverted to achieve that. fe8643262faa8349a689bc8b20a8638887200edd https://github.com/rt2zz/react-native-contacts/commit/fe8643262faa8349a689bc8b20a8638887200edd feel free to submit a PR.
