### ISSUE TITLE
RN 0.60+ permission contacts ios

### ISSUE THREAD

**Issue by Gueoff** [morenoh149/react-native-contacts#429]
Hi!

In react native 0.60 we should add "privacy - contacts usage description" in ios that is not described in README:

Starting with 0.60, the above instructions stop working on iOS. Instead, you have to do the following:

Add the following line inside ios/Podfile

**Comment by morenoh149** [comment]
I'm very interested in your suggestion! It looks like when you pasted it didn't go through. Could you try again
