### ISSUE TITLE
not able to add contact

### ISSUE THREAD

**Issue by prashantbw** [morenoh149/react-native-contacts#438]
```es
var newPerson = {
  familyName: "Nietzsche",
  givenName: "Friedrich",
  phoneNumbers: [{
    label: "mobile",
    number: "(555) 555-5555",
  }],
}

Contacts.addContact(newPerson, (err) => {
  if (err) throw err;
  // save successful
})
```
```
error: java.lang.SecurityException: Permission Denial: writing com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/raw_contacts from pid=17377, uid=10148 requires android.permission.WRITE_CONTACTS, or grantUriPermission()
```

**Comment by morenoh149** [comment]
you need to request permissions before reading. Please read the _entire_ readme before opening issues. https://github.com/rt2zz/react-native-contacts#permissions

**Comment by prashantbw** [comment]
@morenoh149  Ihave given all these permissions in AndroidMainfest.xml
<uses-permission android:name="android.permission.GET_ACCOUNTS" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.READ_PROFILE" />
    <uses-permission android:name="android.permission.WRITE_PROFILE" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />
but still I am facing the same issue,  that's the reason I have opened this issue
   Also  I have gone through the readme you have provided, did follow the procedure , but while adding contact I am facing this issue

java.lang.SecurityException: Permission Denial: writing com.android.providers.contacts.ContactsProvider2 uri content://com.android.contacts/raw_contacts from pid=5219, uid=10148 requires android.permission.WRITE_CONTACTS, or grantUriPermission()

so please need help on this

**Comment by faustoct** [comment]
@prashantbw @morenoh149 How did you fix it?

**Comment by morenoh149** [comment]
Not fixed

**Comment by faustoct** [comment]
@morenoh149 Interesting fact it was working on SAMSUNG A5, SAMSUNG A6 but doesn't on SAMSUNG Galaxy  S7 edge

**Comment by faustoct** [comment]
@morenoh149 it got it working, follow this this https://github.com/LynxITDigital/react-native-contacts-wrapper/issues/42
I'm trying to setup different way to enable permissions

**Comment by faustoct** [comment]
@morenoh149 @prashantbw I fixed it doing this
````
PermissionsAndroid.request(
  PermissionsAndroid.PERMISSIONS.WRITE_CONTACTS
).then(async (response) => {
  await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.READ_CONTACTS)
})
````

**Comment by prashantbw** [comment]
@faustoct  I had fixed it by upgrading my react native from 59.x to 61.x. Glad you found a fix.

**Comment by faustoct** [comment]
@prashantbw glad it worked for you too. I'm using `react-native: 0.61.2` I'd got it working only by doing this.

**Comment by morenoh149** [comment]
ok looks fixed on react-native versions 60 and above. We only support modern react-native versions.

**Comment by nol13** [comment]
still need faustoct's workaround on 0.63.2, but only on a few specific LG devices, all our other phones work fine without it
