### ISSUE TITLE
Contacts.getAllWithoutPhotos() crashes app on samsung galaxy tablet

### ISSUE THREAD

**Issue by lata2694** [morenoh149/react-native-contacts#441]
My app works fine on mobile but the same code breaks on samsung tablet.
```
Contacts.getAllWithoutPhotos((err, contacts) => {
  if (err === 'denied') {
         // error
  } else {
     this.setState({contacts });
  }
});
```
I don't get the reason for app to crash over this. I have acquired permissions before fetching contacts.

**Comment by lata2694** [comment]
I figured it out. doInBackground function needs an extra permission in samsung tablet. It was android.permission.READ_PROFILE

**Comment by ataravati** [comment]
@lata2694 What is that extra permission? Do you mind sharing?

**Comment by lata2694** [comment]
> @lata2694 What is that extra permission? Do you mind sharing?

I suspect the particular tablet I used was reading contacts in different manner (maybe like a profile) as there are two types of contact I can't recall the names precisely (don't have that tablet anymore). I had to add `<uses-permission android:name="android.permission.READ_PROFILE" />` in my manifest to avoid the crash.
