### ISSUE TITLE
Autolinking Support?

### ISSUE THREAD

**Issue by RuairiOliver** [morenoh149/react-native-contacts#442]
react-native: 0.61.2
react-native-contacts: 5.0.4

Hi,

I came across an issue with autolinking.
I created a new app and installed the latest react-native-contacts. I then ran pod install.

After running: npx react-native run-ios
I get this error:
 React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - react-native-contacts

I didn't do any manual linking though, this is a new project and running unlink has no impact. This is the only library I get it with. Any ideas?

I've disabled autolinking for the package for the moment.

Thanks

**Comment by morenoh149** [comment]
so you're using the latest rn that does not require linking. You did not link. And yet you get an error saying you linked?

**Comment by morenoh149** [comment]
the short-term fix is to disable auto linking until we add support for the new linking mechanism in react native https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library PRs welcome

**Comment by morenoh149** [comment]
we need to add a podspec I think

**Comment by RuairiOliver** [comment]
Yes exactly. I'll keep autolinking disabled for now anyway, thanks
