### ISSUE TITLE
Add getContactsByEmailAddress to typescript definitions

### ISSUE THREAD

**Issue by lrahmani-eve** [morenoh149/react-native-contacts#444]

**Comment by morenoh149** [comment]
Needs more info. This Issue will not age well.

**Comment by clintonjrobinson** [comment]
> Needs more info. This Issue will not age well.

I think they are referring to that the definition for getContactsByEmailAddress is missing from react-native-contacts/index.d.ts 

It is however a valid function to call.

**Comment by morenoh149** [comment]
great. We can add that to the ts file pretty easily. Please submit a PR.
