### ISSUE TITLE
Android: phoneNumbers array is Empty

### ISSUE THREAD

**Issue by CoericK** [morenoh149/react-native-contacts#45]
It is given me full array of contacts but all of them have the phoneNumbers array empty, either storing them on the Device or google account.
 Using android 5.0.2

**Comment by lwhiteley** [comment]
seems we posted an issue at the same time #46 .. and follow this one

**Comment by morenoh149** [comment]
please list RN and module versions. Also verify your code works in the Android simulator.

**Comment by lwhiteley** [comment]
RN 0.22.2

started doing a little debugging and the code to populate the stuff not being executed..

https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L89

seems all the values for me are `-1`


ill look into a little more but for now lets assume i don't understand whats going on here :+1:

**Comment by morenoh149** [comment]
@npomfret seems like that line is attributed to you. Any insight into what the issue is?

**Comment by lwhiteley** [comment]
so i changed the following line:
https://github.com/rt2zz/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsManager.java#L39
to 

```java
String selection = ContactsContract.Contacts.HAS_PHONE_NUMBER + " = " + 1;
```

and it still returns a significant list 
(Please note: i had to put a check on all the indexes in this case to check for -1)

Short story: 
It recognizes that these contacts do have phone numbers but when its time to find the actual phone number something goes wrong. 

not sure what that is yet but the contactable mimetype is giving an index of -1 for both emails and phone numbers

@npomfret i see you're the goto guy for this. any ideas?

**Comment by lwhiteley** [comment]
hmm been reading up on this and found a possible solution. ran the code and it works..

i had to requery the phone number sadly..

```java
String id = "";
        if(idColumnIndex != -1){
          id = cursor.getString(idColumnIndex);
          contact.putInt("recordID", Integer.parseInt(id));
        }

        Cursor phones = cr.query(CommonDataKinds.Phone.CONTENT_URI, null,
                CommonDataKinds.Phone.CONTACT_ID + " = " + id, null, null);
        while (phones.moveToNext()) {
          String number = phones.getString(phones.getColumnIndex(CommonDataKinds.Phone.NUMBER));
          int type = phones.getInt(phones.getColumnIndex(CommonDataKinds.Phone.TYPE));
          switch (type) {
            case CommonDataKinds.Phone.TYPE_HOME:

              Log.i("ReactContacts", "TYPE_HOME: " + number);
              // do something with the Home number here...
              break;
            case CommonDataKinds.Phone.TYPE_MOBILE:
              // do something with the Mobile number here...
              Log.i("ReactContacts", "TYPE_MOBILE: " + number);
              break;
            case CommonDataKinds.Phone.TYPE_WORK:
              // do something with the Work number here...
              Log.i("ReactContacts", "TYPE_WORK: " + number);
              break;
          }
        }
        phones.close();
```

**Comment by morenoh149** [comment]
Indeed. The original solution involved multiple cursors. My implementation leveraged the `Contactables` table which allowed a solution involving a single cursor, but with the downsides of 1) requiring a higher api version (than 16+) 2) only being able to return `displayName` instead of firstName and lastName.

@lwhiteley is the multiple cursor solution performant on large number of contacts? (500+) Could you test that? If it is sufficiently performant I think we should restore the multiple cursor approach. If not then we'll have to revert to the `Contactables` approach.

**Comment by lwhiteley** [comment]
ill test in a bit, I'm writing it out into usable code so that i can test it on my phone.

but yea in theory it does sound non-performant but ill see whats up

**Comment by lwhiteley** [comment]
do you have benchmarks? @morenoh149

**Comment by lwhiteley** [comment]
Findings:

### Finding one
Multi cursor approach is taking 32.113 seconds to get 549 contacts

### Finding two

you can resolve your label support easily by using the following snippet

```java

Resources resources = reactContext.getResources();
// For Email
      String label = mCursor.getString(mCursor.getColumnIndex(CommonDataKinds.Email.LABEL));
      CharSequence labelType = CommonDataKinds.Email.getTypeLabel(resources, type, label);
      label = labelType.toString().toLowerCase();

// And for Phone
String label = mCursor.getString(mCursor.getColumnIndex(CommonDataKinds.Phone.LABEL));
      CharSequence labelType = CommonDataKinds.Phone.getTypeLabel(resources, type, label);
      label = labelType.toString().toLowerCase();
```

you can do this instead of trying to map this yourself, that means less effort to support custom code when the mapping is already there

**Comment by morenoh149** [comment]
no benchmarks yet but that sounds perfect for inclusion in https://github.com/morenoh149/react-native-contacts-test

**Comment by pickhardt** [comment]
Is this bug new? I am just noticing it now, although I had used the library previously with real Android phones and it worked fine.

**Comment by rt2zz** [comment]
@pickhardt I believe accessing contacts is a fundamentally slow operation on ios and android (please correct me if I am wrong, obviously we would love to make it faster!).

I believe the solution is rather than calling `getAll` to implement methods along the lines of `get({limit: 10})` and `search({name: 'a'})` or something along those lines.

**Comment by pickhardt** [comment]
While I've never done it, this code read straightforwardly and they say it took about half a second:
http://www.blazin.in/2016/02/loading-contacts-fast-from-android.html

I just have never used an app that took more than a second to load contacts, so there must be some trick that everyone is using.

**Comment by morenoh149** [comment]
indeed loading all the contacts on a device can become slow if there are many contacts. Hence why I like the solution that only performed one query agains the `Contactables` table. A solution would be to allow limit and offsetting to the query as @rt2zz said.

**Comment by lwhiteley** [comment]
@pickhardt unfortunately that was the similar code that wasn't working in this scenario.

However, i managed to improve the performance a bit.

i reduced the time with same amount of contacts from 30+ seconds to `12.448` seconds.

**Comment by rt2zz** [comment]
@lwhiteley do you feel your fork is near a place where we can look at doing a PR/merge?

Are there any other changes other than obviously being much faster?

**Comment by lwhiteley** [comment]
nah it gives back the desired results according to the docs.. ill submit a PR and you can review

**Comment by morenoh149** [comment]
I need to benchmark that against the old solution. My app is not taking ~10 seconds to load all contacts on a device (500+ contacts).

**Comment by lwhiteley** [comment]
yup fire away.. as long as its loading all numbers and emails then its a good comparison.
someone should also test the timing on IOS as well

**Comment by lwhiteley** [comment]
it would be good to create a `.get( options , cb)` so we can options to either
get contacts with the numbers and emails etc.
filter the contacts etc

this may be good if I want to lazyload the emails and numbers later on
