### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by mayankmittal242** [morenoh149/react-native-contacts#452]
Giving a array without any sorting, There should be a fixed sorting order

**Comment by morenoh149** [comment]
can you give an example? This may not be possible, we can only do what the operating systems allow.

**Comment by FDiskas** [comment]
It could help
https://stackoverflow.com/a/13814897/175404

**Comment by willnaoosmit** [comment]
I tried with this, and worked:
  loadContacts() {
    Contacts.getAll((err, contacts) => {
      if (err === "denied") {
        this.setState({estado: 'denied'})
        return
      } else {
        
        Contacts.getCount(count => {
          if (count < 400){
            contacts.sort((a,b)=> (a.givenName > b.givenName) - 1)
          } else {
            contacts.sort((a,b)=> (a.givenName > b.givenName))
          }
        })

        this.setState({ contacts });
      }
    });

But the problem i'm facing it's performance.
Can you put the sort algorithm on the code itself?
with java.

**Comment by FDiskas** [comment]
This should be done in java

**Comment by morenoh149** [comment]
PRs welcome. Be sure to implement the ios side as well.

**Comment by FDiskas** [comment]
We are simple users, no knowledge about iOS and Android side. :)

**Comment by FDiskas** [comment]
Yes, wait more and problem will be solved

**Comment by willnaoosmit** [comment]
I will be working on it when i got time. But that's not the case :(
