### ISSUE TITLE
openContactForm Keyboard is visible by default.

### ISSUE THREAD

**Issue by AlkanV** [morenoh149/react-native-contacts#459]
When we call openContactForm, it works as expected but with little bug. It opens the contact form with keyboard visible. I want it unvisible as default. is there any config for that?

**Comment by morenoh149** [comment]
no config for that. Please add.

**Comment by andriinegustorov** [comment]
some progress on this?

**Comment by morenoh149** [comment]
@andriinegustorov none yet. Feel free to pitch in.
