### ISSUE TITLE
Android thumbnail image issue

### ISSUE THREAD

**Issue by prasidhda** [morenoh149/react-native-contacts#473]
In android , We are receiving thumbnail path as content://com.android.contacts/contacts/537/photo.

We have used following code to render contact image -
<Image source={{ uri: "content://com.android.contacts/contacts/537/photo" }} />

But It is not displaying Contact Image.
I think it is not displaying due to non HTTPS thumbnail path. 
Please help me out here.

**Comment by morenoh149** [comment]
look into https://stackoverflow.com/questions/36259339/convert-content-uri-to-actual-path-for-android-using-react-native
