### ISSUE TITLE
Phone number labels other than "mobile", "home", "work" are reported as "other"

### ISSUE THREAD

**Issue by minuhariharan** [morenoh149/react-native-contacts#484]
I added some custom phone number labels for my contact e.g. "This is a very big label" but it appears as "other" when I fetch the list of contacts. Some other labels for phone numbers on the phone like "Work fax", "Home fax" etc.. appear as other. I tested and found that only "mobile", "home", "work" as reported as is and all other labels show up as "other". Is there any solution to this issue?  I am using react-native-contacts v 4.0.3

**Comment by morenoh149** [comment]
firstly you should be on v5.x.x by now.
second, what platforms are you seeing this on?

**Comment by minuhariharan** [comment]
Ok will upgrade to v5, I found this issue on Android - Android Emulator to be specific, have not yet tried it on iOS.

**Comment by morenoh149** [comment]
ok. Please test it on ios if you can.
