### ISSUE TITLE
Thumbnail is not present when fetching contact by id on iOS

### ISSUE THREAD

**Issue by Ackuq** [morenoh149/react-native-contacts#486]
### Describe the bug
When calling the function `getContactById(contactId, callback)` on iOS the thumbnail path is not included in the returned object, even though the `hasThumbnail` bool is set to `true`.

### Expected behavior
The thumbnail path to be included and accessible through the `thumbnailPath` property of the returned object.

### Workaround
Check whether `hasThumbnail` is set to true and that the platform is iOS and then call `getPhotoForId(contactId, callback)` to get the photo.

### Smartphone
- Device: iPhone 11 (Simulator)
- OS: 13.3

**Comment by heyalexchoi** [comment]
having same issue. 
using `getAllWithoutPhotos` to populate a list
and then `getContactById` to get data for a detail view. expected `thumbnailPath` to be included in the result but it's not.
