### ISSUE TITLE
Cannot access notes (iOS)

### ISSUE THREAD

**Issue by BeHotSiii** [morenoh149/react-native-contacts#488]
We've recently upgraded from `5.0.1` to `5.0.7`. Unfortunately we discovered that getting/setting the contact's notes isn't supported any more since `5.0.2`. After reverting the commit `02db1fef8200eeb26f1e1362ccd93baca772e0bf`and testing the code on multiple devices with various iOS-version, everything seemed to work fine.

According to the comments, the functionality was removed because _"Apple doesn't allow access to the notes field on iOS 13"_ . This is not true! Following the apple docs, adding an entitlement file including the `com.apple.developer.contacts.notes` entitlement should work just fine: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_contacts_notes?language=objc

Would it be possible to revert the removal of the note feature and add a hint in the RadMe.md to add the missing entitlement?

**Comment by morenoh149** [comment]
yes please submit those changes in a PR

**Comment by BeHotSiii** [comment]
Alright. PR https://github.com/morenoh149/react-native-contacts/pull/490 has been added :)
