### ISSUE TITLE
iOS - Dev mode: access to contacts, Release mode no contacts

### ISSUE THREAD

**Issue by Pandazaur** [morenoh149/react-native-contacts#495]
Hello,

I'm developing an app with React Native and I'm struggling with the access to the contacts

I'm using

```
"react": "16.8.3",
"react-native": "0.59.9",
"react-native-contacts": "^3.1.4",
```

When trying my app on Android or the iOS simulator I can access to my contacts but when I release my iOS app: I have the alert to allow permissions and then nothing happen ... No contacts in the list.

Do someone have an idea about why I could not access to my contacts ONLY in my iOS app releases ?

**Comment by morenoh149** [comment]
please try react native latest (60+) and rnc latest 5.0.7. Older versions are unsupported.

**Comment by sandeepmanegs** [comment]
@morenoh149 
Hello, I facing same issue

"react-native": "0.61.5",
"react-native-contacts": "^5.1.0",

@Pandazaur did you find any solution for this?
