### ISSUE TITLE
How to open phone contacts screen ?

### ISSUE THREAD

**Issue by MustaphaGhlissi** [morenoh149/react-native-contacts#497]
Hi, 

Does there any way to open the phone contacts screen ? Default UI

Regards !

**Comment by MustaphaGhlissi** [comment]
I found a solution finally by using Linking module like this:

`Linking.openURL('content://com.android.contacts/contacts')`


Hope that can help any one else !

**Comment by Suhasini9663** [comment]
where to link Linking.openURL('content://com.android.contacts/contacts')
