### ISSUE TITLE
Contacts.iosEnableNotesUsage(true) is not a function

### ISSUE THREAD

**Issue by minh-dai** [morenoh149/react-native-contacts#503]

**Comment by morenoh149** [comment]
how are you determining it's not a function? it is documented. You must run a version of react-native-contacts that _has_ the function. Needs more details.

**Comment by neilanthonyte** [comment]
i just added in the index.ts below removeContactsFromGroup

```
async function iosEnableNotesUsage(enabled: boolean) {
  return Contacts.iosEnableNotesUsage(enabled);
}
```

then at the bottom of the export default `iosEnableNotesUsage`

hope they will fix the library
