### ISSUE TITLE
Calling updateContact on Samsung S8 makes contact un-editable from Samsung Native Contact App

### ISSUE THREAD

**Issue by JohnWebb4** [morenoh149/react-native-contacts#504]
# Description

On an Android Samsung, S8 and S10 if you call updateContact it will make the contact un-editable from the Samsung native contact app.

# Affected
Android users on Samsung S8 and S10. Maybe more Samsung models.

# Technical
I believe it is because ACCOUNT_TYPE and ACCOUNT_NAME are set on updateContact. [Android docs](https://developer.android.com/reference/android/provider/ContactsContract.RawContacts) (See ContactsContract.SyncColumns.ACCOUNT_TYPE) warn against updating the ACCOUNT_NAME and ACCOUNT_TYPE later.

# How to test

These are my steps to reproduce on S8.

- Create contact using addContact method
- Update that contact's first name and last using updateContact
- Close the React Native application and open the S8 native contact app
- Search for the created contact and click to go to details
- If you tap edit, at the bottom of the page it will crash the native contact app

**Comment by minh-dai** [comment]
same issues :((
