### ISSUE TITLE
Contacts.getAll crash (iOS); attempt to insert nil object into NSArray

### ISSUE THREAD

**Issue by benanderman** [morenoh149/react-native-contacts#510]
I haven't been able to reproduce this issue locally, but we have gotten a lot of crash reports for it. It's hard to say how many, because we're using Sentry, and they don't group this properly, but happens often multiple times per day.

This is the log message:
```
RCTFatalException: Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]' was thrown while invoking getAll on target Contacts with params (
    10847
)
```

**Comment by morenoh149** [comment]
the fix in https://github.com/morenoh149/react-native-contacts/pull/430 fixes the issue inside `getContact:(NSString *)recordID`

that error is about `getAll`. `getAll` calls out to `getAllContacts` (https://github.com/morenoh149/react-native-contacts/blob/master/ios/RCTContacts/RCTContacts.m#L246)

`getAllContacts` calls out to `retrieveContactsFromAddressBook`.  I don't see anywhere in retrieveContactsFromAddressBook where it would be reading a contact by a passed in id.

**Comment by benanderman** [comment]
Thanks for responding so quickly! I don't think that param is an ID, I think it's somehow a representation of a callback. Note, we're on version 4.0.3, so it's possible this is already fixed.

Looking through the code, I can only find one possible (but seems unlikely) scenario where this could happen, and if that's it, it's already fixed by this line:
https://github.com/morenoh149/react-native-contacts/blob/master/ios/RCTContacts/RCTContacts.m#L1064

In 4.0.3, that check was only made when creating a new store, but now it's always checked. If we already had a store, but it somehow no longer had a `defaultContainerIdentifier`, then I believe we would see this crash on `@[contactStore.defaultContainerIdentifier]` in `retrieveContactsFromAddressBook:withThumbnails:withCallback`.

**Comment by morenoh149** [comment]
oh yeah. I don't even want to have this discussion unless you are running the latest version. Please get back to me once you have update your project and other deps :)
