### ISSUE TITLE
Contacts.GetAll() returns 0 contacts on ios

### ISSUE THREAD

**Issue by willnaoosmit** [morenoh149/react-native-contacts#511]
I'm running your example project on ios 13.3 (a iphone 11 emulator, and a iphone 8 device) and the function getAll doesn't return any contacts, and i really have some contacts on both devices.

My system info:

```
    OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
    Memory: 26.20 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.npm-packages/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.3.1/11C505 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_242 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Commands i ran:

```
git clone https://github.com/morenoh149/react-native-contacts.git
cd react-native-contacts/
npm install --save
cd example/
npm install --save
sudo npm cache clean -f && npm install --save 
clear
cd ios
pod install
cd ..
react-native run-ios
```

Screenshot:
![Captura de Tela 2020-04-23 às 16 37 35](https://user-images.githubusercontent.com/55159911/80142178-210d0c00-8581-11ea-9643-02e5a86ef3e7.png)

Screenshot of the contacts:
![Captura de Tela 2020-04-23 às 16 44 08](https://user-images.githubusercontent.com/55159911/80142535-ae506080-8581-11ea-82a6-af8399db67a1.png)

Also, thanks for being an active user and keeping the project up.
I will be grateful if you can help me!

**Comment by willnaoosmit** [comment]
Also:

On package.json of the project there's:

```
"react-native-contacts": "https://github.com/rt2zz/react-native-contacts.git",
```

It should be the npm package instead, right?

**Comment by morenoh149** [comment]
no this is so that it always pulls from master. It should be updated to use a different user. I'll change it.

**Comment by vpjacob** [comment]
I have same issue

**Comment by willnaoosmit** [comment]
Well, this is akward, but find out that is the line `Contacts.iosEnableNotesUsage(true);` on the file `App.js` of the example wich is giving the error of returning 0 contacts.
Maybe it's an error on the `RCTContacts.m` file.

Hope it helps on the debugging @morenoh149

**Comment by willnaoosmit** [comment]
I figured it out using the [fmurtadho](https://github.com/fmurtadho/react-native-contacts/blob/master/ios/RCTContacts/RCTContacts.m) fork wich is kinda recent,. So i guess you can use a [DiffChecker](https://www.diffchecker.com/) to find out the differences between the two files.

**Comment by morenoh149** [comment]
the difference is that it uses `android.support` and not `androidx` https://github.com/morenoh149/react-native-contacts/compare/master...fmurtadho:master 

See more https://stackoverflow.com/questions/50338323/difference-between-androidx-and-com-android-support

I don't think using android.support is the correct solution.

**Comment by alvarocs92** [comment]
que paso con la solucion?

**Comment by willnaoosmit** [comment]
@alvarocs92 just dont use `Contacts.iosEnableNotesUsage(true);` on your code and it will work.

**Comment by alvarocs92** [comment]
@willnaoosmit ok thanks !!, And how did you solve the search engine, since it does not look for me in ios but in android yes??
