### ISSUE TITLE
iOS: Deleting Contact should close card

### ISSUE THREAD

**Issue by danwhite-ipc** [morenoh149/react-native-contacts#514]
When deleting a native contact the contact form is not closing

**Comment by danwhite-ipc** [comment]
Do you need more information to replicate? Is happening in v5.2.0

**Comment by morenoh149** [comment]
if you could fix the objective-c and submit a pr that would be great. What we really need is someone with time and ability.

**Comment by danwhite-ipc** [comment]
Any reason when running the example in iOS simulator it loads 0 contacts when the device has contacts?

**Comment by morenoh149** [comment]
must be a bug. I see the same this in the ios sim when I test it out.

**Comment by danwhite-ipc** [comment]
I have tired to look at the native code to try and fix this issue but unable to find a solution, someone better than me might.

**Comment by danwhite-ipc** [comment]
This bug is about the delete not dismissing the card

**Comment by danwhite-ipc** [comment]
I am still finding this is an issue
