### ISSUE TITLE
How to combine "react-native-communications" and "react-native-contacts" ??? 

### ISSUE THREAD

**Issue by chegmarco1989** [morenoh149/react-native-contacts#515]
Hello.

I would like to combine the "React-Native-Contacts" Library ( https://github.com/morenoh149/react-native-contacts) and "React-Native-Communications" (https://www.npmjs.com/package/react-native-communications) to directly select and call my contacts already registered in the Directory of My phone. The problem is that I don't know how to do this by modifying the "**OnPress**" props of "**App.js**" code from the "**React-Native-Contacts**" library which is "**onPress={() => Contacts.openExistingContact(contact, () => { })}**" by assigning that of the Components "Communications" which calls to "**Communications.phonecall('0123456789', true)**". The goal is therefore to modify the telephone number "_0123456789_" by the selected Contact from my Mobile Phone Directory.

Help me solve this puzzle by successfully combining the two Libraries  "React-Native-Contacts" ( https://github.com/morenoh149/react-native-contacts)   and "React-Native-Communications" (https://www.npmjs.com/package/react-native-communications) because this Tutorial that explains how to use "React-Native-Communications" (https://aboutreact.com/make-phone-call-send-sms-or-email-using-react-native-communication/) does not detail how to do it work with the contacts of our mobile phone.

Please help me.

**Comment by morenoh149** [comment]
please share a repo that we can clone to help you.

**Comment by chegmarco1989** [comment]
Hello Sir.

 Here is the link from the Github repository of the "React-native-communications" library that I would like to use with the example of "React-native-contacts" in order to allow access to the entire contacts directory on the phone of the  phone and select a contact from all those on the list and call them:


 https://github.com/anarchicknight/react-native-communications/blob/master/README.md

**Comment by chegmarco1989** [comment]
Hello Sir and Thank you for your reply.

Here is the link from the Github repository of the
"React-native-communications" library that I would like to use with the
example of "React-native-contacts" (
https://github.com/morenoh149/react-native-contacts/blob/master/example/App.js)
in order to allow access to the entire contacts directory on the phone of
the phone and select a contact from all those on the list and call them:

https://github.com/anarchicknight/react-native-communications/blob/master/README.md

**Comment by morenoh149** [comment]
please make a repo for you that uses react-native-contacts and react-native-communications. Then we can clone that and help you.

**Comment by morenoh149** [comment]
closing as we are not responsible for react-native-communications
