### ISSUE TITLE
Avoid duplication if a contact already exists

### ISSUE THREAD

**Issue by tinyCoder32** [morenoh149/react-native-contacts#517]
Hi, is there a way to avoid adding the contact if their phone number already exists in the phone book?

**Comment by morenoh149** [comment]
not yet. PRs welcome.

**Comment by tinyCoder32** [comment]
The function accepts adding the same exact contact multiple times, what is the proper way to avoid that?

**Comment by morenoh149** [comment]
one thought is to loop over all the contacts and check before attempting to store the new contact. There is no issue here. If you have questions please use stackoverflow and ping me to answer there.

**Comment by tinyCoder32** [comment]
That is the worst thought, specially that most of my customers have at least 10K contacts.

Thanks anyway.

**Comment by morenoh149** [comment]
If you want to and api that can aid in checking. Please open an issue for that and submit a PR implementing the new api.
