### ISSUE TITLE
Contact list does not contain the phone number of the device owner (iOS)

### ISSUE THREAD

**Issue by KristineTrona** [morenoh149/react-native-contacts#518]
Hi, on iOS if you go to Settings -> Contacts, you can set your own contact here:

![IMG_3844](https://user-images.githubusercontent.com/39855778/82231267-35001f80-992d-11ea-9278-e9fb6496c1fe.png)

Which is visible when you open the contacts on the device:

![IMG_3845](https://user-images.githubusercontent.com/39855778/82231271-36314c80-992d-11ea-843e-f4e1fd39f77f.png)

However, this contact is not distinguishable in any way from the rest of the contacts in the list. 
For the project that I am currently working on it would be nice to be able to distinguish this contact somehow from the others. I could do so on the basis of phone number, only **this contact also does not return a phone number** even though clicking on the contact card does actually show one:

<img width="198" alt="Screenshot 2020-05-18 at 17 21 47" src="https://user-images.githubusercontent.com/39855778/82230473-0fbee180-992c-11ea-8955-b0edf7651815.png">

![Image from iOS](https://user-images.githubusercontent.com/39855778/82231258-329dc580-992d-11ea-865d-02d24eccd679.png)

Any way to fix this? Or any other way to access the user set in the iOS settings?

**Comment by morenoh149** [comment]
No way as far as I know. Might require an objective-c code change and I don't dedicate much time to this Lib. Happy to point you in the right direction though!
