### ISSUE TITLE
Contacts.getAllPhoneNumbers - Feature Request 

### ISSUE THREAD

**Issue by shivnath17** [morenoh149/react-native-contacts#519]
For people like me who only need phone numbers and names. Can we add a separate method (`Contacts.getAllPhoneNumbers`) for getting all the phone numbers and associate names. Currently  we do `Contacts.getAll()` but facing performance issue.

**Comment by morenoh149** [comment]
would be great to specify the column (paths) you want to getAll

`getAll(['telephone', 'first_name', 'last_name'])`.

**Comment by morenoh149** [comment]
it would also be good to specify a custom where clause to narrow down the number of rows in the resultset.
AND, it would be good to expose a cursor (pagination) so the application can process n items at a time.

**Comment by NicholusMuwonge** [comment]
Hey @morenoh149  `getAll()` method doesn't seem to take in any arguments and I get an error when I pass in any arguments

> would be great to specify the column (paths) you want to getAll
> 
> `getAll(['telephone', 'first_name', 'last_name'])`.

**Comment by morenoh149** [comment]
@NicholusMuwonge needs to be added to the library. PRs welcome.

**Comment by nataliialapshyna-dna** [comment]
@morenoh149 Hi, I would like to create PR would this feature. What do you expect as return value for `getAll(['telephone', 'first_name', 'last_name'])` function? The same list of `Contact` objects as for `getAll()` but with empty fields, or something different?

**Comment by morenoh149** [comment]
@nataliialapshyna-dna I would expect the same list of Contact objects as for getAll() but with missing fields. so
```es
getAll(['phoneNumbers', 'givenName', 'familyName'])

returns

[
 {
  recordID: '6b2237ee0df85980',
  familyName: 'Jung',
  givenName: 'Carl',
  phoneNumbers: [{
    label: 'mobile',
    number: '(555) 555-5555',
  }],
  },
  ...
]
```
