### ISSUE TITLE
React/RCTBridgeModule.h error during build process. 

### ISSUE THREAD

**Issue by honey93** [morenoh149/react-native-contacts#524]
Getting RCTBridgeModule.h error while migrating from React-Native 0.59.9 to 0.62.2 

![image](https://user-images.githubusercontent.com/10286968/84161365-d4c44f80-aa8c-11ea-8e01-50373e450bcd.png)

Have added in Podfile also. 

pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

Followed certain StackOverflow posts also: https://stackoverflow.com/questions/41663002/react-rctbridgemodule-h-file-not-found

**Comment by leandromds** [comment]
I have the same problem.

**Comment by morenoh149** [comment]
rn v60 was a huge fiasco. Study https://github.com/mikehardy/jetifier not sure what you will have to do exactly but if you were to start a fresh project on the right side of rn 60 (any version above 60) things work.
