### ISSUE TITLE
Unable to fetch Contacts iOS 13.4 + iOS 13.0 (simulator)

### ISSUE THREAD

**Issue by mzain512** [morenoh149/react-native-contacts#526]
Need help 

Getting empty array when fetching contacts 
Permission is authorized but still getting zero contacts
I am using methods getAll & getAllWithoutPhotos
using version for lib is 5.0.0

Note: Its working on iOS 12.1 simulator but not working for any device above 13 i guess.

**Comment by jcargilo** [comment]
I was just trying the example on my _iPhone 8+_ and can confirm that it isn't receive contacts either (iOS 13.5.1).

**Comment by mzain512** [comment]
To add more detail I was able to fetch contacts for above mentioned versions after updating library to 5.2.0. If helpful for anyone kindly try it.

**Comment by alvarocs92** [comment]
Contacts.iosEnableNotesUsage(false);

**Comment by mzain512** [comment]
Contacts.iosEnableNotesUsage(false); isn't supported in 5.0.0

**Comment by morenoh149** [comment]
we are really only focused on supporting the latest versions of rn and ios. Thanks for this.
