### ISSUE TITLE
Semantic issue when run in IOS

### ISSUE THREAD

**Issue by Tiepbm** [morenoh149/react-native-contacts#529]
Hello,
I have errors when run ios
React native: 0.62.2
XCode: 10.1
MacOS Hight Sierra 10.13.6
I run android success, but It has errors when I run ios. Here is error:
<img width="513" alt="38F713E9-4506-42A5-9E3E-9C5ED32B6C0E" src="https://user-images.githubusercontent.com/3059239/85530635-49c08900-b638-11ea-9d9f-74d5a9269f34.png">
Any way to fix this?

**Comment by morenoh149** [comment]
I have not seen this

**Comment by Tiepbm** [comment]
Isssue fixed when I updated masOS to mojave and Xcode 11.
Thanks!
