### ISSUE TITLE
[Need Help] How can I optimize fetching when we have contacts around 6k 

### ISSUE THREAD

**Issue by mzain512** [morenoh149/react-native-contacts#531]
I am working on an app where I am fetching contacts. My client faced an issue where he said I have 6k contacts and UI isn't updating.

I using `getAll` method

Need suggestion how can I optimize fetching. Is there any build in function for this?

**Comment by morenoh149** [comment]
please submit a PR. We have a ticket for this enhancement https://github.com/morenoh149/react-native-contacts/issues/519
