### ISSUE TITLE
[iOS] 5.2.2 is not tested, lol

### ISSUE THREAD

**Issue by ObidosDev** [morenoh149/react-native-contacts#532]
Looks like contactError is used, but was removed. Did some one try to run it even once?

<img width="1149" alt="Screenshot 2020-06-26 at 20 37 14" src="https://user-images.githubusercontent.com/16224235/85885447-02c7c480-b7ed-11ea-87e8-b1dccacb22ba.png">

![Screenshot 2020-06-26 at 20 37 22](https://user-images.githubusercontent.com/16224235/85885450-052a1e80-b7ed-11ea-8c54-63be3ccc46f3.png)

**Comment by jamesjara** [comment]
Yep, CD/CI Failing because of this

```

    "react-native-contacts": "~5.1.0",
```

**Comment by morenoh149** [comment]
fixed in 5.2.3, this is a community project and we depend on contributors
