### ISSUE TITLE
null is not an object (evaluating '_reactNativeContacts.default.getAll')  in android 

### ISSUE THREAD

**Issue by pkpardeep482** [morenoh149/react-native-contacts#539]
React-Native : 0.62.2 
Android version : 9 

Using it list this way 
```
import Contacts from 'react-native-contacts';
Contacts.getAll((contacts) => {
      console.log('---', contacts);
    });
```

**Comment by morenoh149** [comment]
did you request permissions like the readme says?

**Comment by pkpardeep482** [comment]
Yes. Permissions r allowed

**Comment by morenoh149** [comment]
duplicate https://github.com/morenoh149/react-native-contacts/issues/220 please ask question on stackoverflow
