### ISSUE TITLE
Phone numbers are not getting from Contacts.getAll() function. 

### ISSUE THREAD

**Issue by Utkarshkataria** [morenoh149/react-native-contacts#550]

**Comment by Utkarshkataria** [comment]
its getting
company : ""
department : ""
displayName : "random"
emailAddresses
familyName : "random"
givenName : "random"
hasThumbnail : false
imAddresses
jobTitle : ""
middleName : ""
note : ""
phoneNumbers
0
0 : function
1
postalAddresses
prefix : null
rawContactId : "169"
recordID : "169"
suffix : null
thumbnailPath : ""
urlAddresses

**Comment by Google987** [comment]
Hi,
Is this bug still there? If yes, any advice on how I can contribute to this?

**Comment by morenoh149** [comment]
@Google987 bug is still probably there. Feel free to patch and submit a PR.
