### ISSUE TITLE
Contact search insensitive 

### ISSUE THREAD

**Issue by yelena870513** [morenoh149/react-native-contacts#555]
I would like how to make search case insensitive using methods
* getContactsMatchingString
* getContactsByEmailAddress

**Comment by yelena870513** [comment]
To give further details, I forked the repo  and tried:

- Use COLLATE (NOCASE, LOCALIZED) appending this value to select query.
- Use LOWER and UPPER combined with similar functions on Java to set up one case on string.
- Use REGEXP (It doesn't work on Android) 
- Alternate CONTENT_URI but it has constrains to Level API


As device I am using
- Android 8.0 on Xiamo Redmi 6A

**Comment by morenoh149** [comment]
I would recommend getting this working at the sqlite level. looks like sqlite already does case insensitive matching with the `like` operator https://www.db-fiddle.com/f/s78oU3TYArR35eFjfScERE/0

did you try that?

**Comment by yelena870513** [comment]
Thanks for heads up, maybe it is related to my phisical device. Will set up further tests, but all available I got are Redmi devices. Thaks for your time.

> I would recommend getting this working at the sqlite level. looks like sqlite already does case insensitive matching with the `like` operator https://www.db-fiddle.com/f/s78oU3TYArR35eFjfScERE/0
> 
> did you try that?

**Comment by yelena870513** [comment]
> do you think the lib needs this PR. Happy to merge if it improves the lib.

I believe it needs further research, because right now blockers in case sensitive search is bound to device and language. I need more information to correlate collate and Android specific database. I think no need more action besides this for the moment. If so in future will open a new PR with a proper explanation
