### ISSUE TITLE
SIGABRT Error

### ISSUE THREAD

**Issue by martellapetesso** [morenoh149/react-native-contacts#562]
Hi everybody, 

i have the following issue. I got everytime the signal SIGABRT Error in Xcode if i call the requestPermission() method.
Thanks in advance.

<img width="1047" alt="Screenshot 2020-10-05 at 09 39 24" src="https://user-images.githubusercontent.com/48688668/95052703-adeef080-06ef-11eb-9042-20bf1937f07d.png">

**Comment by morenoh149** [comment]
what xcode, what react native version, etc.

**Comment by martellapetesso** [comment]
Oh sorry:

- xCode: 12.0.1 (12A7300)
- RN: 0.62.2
- tested on: iOS 13 and iOS 14 on iPhone 11 Pro Simulator
- react-native-contacts: 5.2.7
- macOS Catalina 10.15.6

**Comment by martellapetesso** [comment]
Have any idea?

**Comment by morenoh149** [comment]
no ideas yet

**Comment by martellapetesso** [comment]
if(Platform.OS === 'ios') {

            Contacts.checkPermission((_, permission) => {

                if (permission === 'undefined') {
                    Contacts.requestPermission((err, permission2) => {
                        console.log("PERM: ", permission2)
                    })
                  }
            })

        } else {
            PermissionsAndroid.request(
                PermissionsAndroid.PERMISSIONS.READ_CONTACTS,
                {
                  'title': 'Contacts',
                  'message': 'This app would like to view your contacts.',
                  'buttonPositive': 'Please accept bare mortal'
                }
              ).then(() => {
                Contacts.getAll((err, contacts) => {
                  if (err === 'denied'){
                    console.log("DENIED")
                  } else {
                    console.log("CONTACTS: ", contacts)
                  }
                })
              })
        }
