### ISSUE TITLE
 iOS - Exception: 'The RCTPromiseResolveBlock must be the second to last parameter

### ISSUE THREAD

**Issue by bevanmw** [morenoh149/react-native-contacts#566]
Version Details:
RN: 0.61.5
react-native-contacts: 6.0.1
iOS: 14.0.1

Description:
Calling openContactForm on iOS results in exception: 'The RCTPromiseResolveBlock must be the second to last parameter in - [RCTContacts openContactForm:resolver:]'

Expectation:

No exception is thown.

Actual behavior:

Calling openContactForm on iOS results in exception: 'The RCTPromiseResolveBlock must be the second to last parameter in - [RCTContacts openContactForm:resolver:]'

**Comment by liukaren** [comment]
(Also getting a similar error with `checkPermission`)

> Exception 'The RCTPromiseResolveBlock must be the second to last parameter in -[RCTContacts checkPermission:]' was thrown while invoking checkPermission on target Contacts
