### ISSUE TITLE
Update contact details nothing happens

### ISSUE THREAD

**Issue by Jalson1982** [morenoh149/react-native-contacts#568]
Hello,

I want directly from application when user update shipping details to add missing fields in phonebook like address, city etc.

Here is sample code:
```
Contacts.getAllWithoutPhotos((err, contacts) => {
    const findContact = contacts.find(contact => contact.recordID === recordID);
    const updatedFields = {
            city: shippingDetails.city,
            postCode: shippingDetails.zip,
            addressLine1: shippingDetails.address1,
            addressLine2: shippingDetails.addressLine2,
            region: shippingDetails.province
     };
    if (findContact) {
        findContact.postalAddresses.push(updatedFields);
                Contacts.updateContact(findContact,(err)=>console.log(err))
         }
});
```
But it does not. What I am missing?

**Comment by morenoh149** [comment]
I find it a bit hard to understand you.

**Comment by Jalson1982** [comment]
Ok, let's explain it. I have a shipping form in my app and I pull user details from the phone. Most of the time I do not have in the phonebook address of the user and when I fill it I want also to update that contact on my phone and add an address. I used Contacts.updateContact(findContact,(err)=>console.log(err)) but it does not update address at all. That is a problem.

**Comment by Jalson1982** [comment]
is it clear now @morenoh149 ? Basically, I just want on some action update contact in the phonebook with a new postal address. I tried with the ios simulator but nothing happens :(.
