### ISSUE TITLE
openContactForm does nothing -  release 4.0.2

### ISSUE THREAD

**Issue by AllanLotta** [morenoh149/react-native-contacts#569]
I saw the fix for this bug on #567 in the latest version. 
I try to copy this solution to version 4.0.2 but i don't have success.

It's the same issue?
how can i fix it for 4.0.2?

react-native: 0.59.9

**Comment by morenoh149** [comment]
that pr adds a promise to the api. Doesn't make sense to backport that into 4.0.2 locally. Are you sure you understand your problem?

**Comment by AllanLotta** [comment]
i will explain my problem: I am using the version 4.0.2 and on the method openContactForm don't open on IOS. 
don't open the form and don't show any error

`
const newPerson = {
      emailAddresses: [{
        label: "work",
        email: "mrniet@example.com",
      }],
      familyName: "Nietzsche",
      givenName: "Friedrich",
    };
    
    Contacts.openContactForm(newPerson, (err) => {
      console.log("err", err);
      if (err) throw err;
      // save successful
    })`
