### ISSUE TITLE
address book update notification callback event listener

### ISSUE THREAD

**Issue by msftsvachon** [morenoh149/react-native-contacts#57]
I'm not sure if this is something being tracked already, but thought I'd document here. It'd be nice to add support for address book update callback.

For instance on iOS:
http://stackoverflow.com/questions/29208605/how-to-get-notified-in-contact-changed-event-in-ios/29208841#29208841

**Comment by morenoh149** [comment]
PR welcome!

**Comment by aadityapaliwal94** [comment]
Thanks for this great library. Any progress for this feature or ETA?

**Comment by morenoh149** [comment]
@aadityapaliwal94 no progress. Feel free to add the feature.

**Comment by vivek0046** [comment]
any update?
