### ISSUE TITLE
Exception when using Contacts.checkPermission - 6.0.2

### ISSUE THREAD

**Issue by florinleu** [morenoh149/react-native-contacts#570]
react-native 0.63.3
react-native-contacts 6.0.2
iOS 13.7

Trying to use the sample code on iOS throws "The RCTPromiseResolveBlock must be the second to last parameter".
```
Contacts.checkPermission().then(permission => {
  // Contacts.PERMISSION_AUTHORIZED || Contacts.PERMISSION_UNDEFINED || Contacts.PERMISSION_DENIED
  if (permission === 'undefined') {
    Contacts.requestPermission().then(permission => {
      // ...
    })
  }
  if (permission === 'authorized') {
    // yay!
  }
  if (permission === 'denied') {
    // x.x
  }
})
```

**Comment by morenoh149** [comment]
not sure. Skimming https://github.com/morenoh149/react-native-contacts/blob/6f0009ea0fbd57703616641e7969d0cafd87404b/ios/RCTContacts/RCTContacts.m @mateosilguero
