### ISSUE TITLE
has anyone had problems on iOS with Dual Sim in particular an eSim

### ISSUE THREAD

**Issue by chrishawn** [morenoh149/react-native-contacts#573]
here's info on the feature [https://support.apple.com/en-us/HT209044](https://support.apple.com/en-us/HT209044)

it seems you can assign contacts to a preferred sim, i have an international user that has this setup and contacts don't seem to return. 

not even sure where to start debugging, works for everyone else it seems.

**Comment by morenoh149** [comment]
no clue
