### ISSUE TITLE
Android release Error JS Functions are not convertible to dynamic

### ISSUE THREAD

**Issue by nguyenvanquan7826** [morenoh149/react-native-contacts#574]
Hi, Today I build release apk by android studio and when call `Contacts.checkPermission`, it error **JS Functions are not convertible to dynamic**. Please help me fix this bug. Thanks

**Comment by morenoh149** [comment]
not sure. We recently released v6.x to use promises. If you are not ready to upgrade please pin your dependency version to v5.x.
