### ISSUE TITLE
Error to install - version 4.0.2

### ISSUE THREAD

**Issue by AllanLotta** [morenoh149/react-native-contacts#575]
I am trying to install the version 4.0.2 to IOS 

but i get an error on step 3: 
"In the XCode project navigator, select your project, select the Build Phases tab drag Libraries > RCTContacts.xcodeproj > Products > libRCTContacts.a into the Link Binary With Libraries section. Video to clarify Adding Camera Roll to an ios project in React Native"

when i drag libRCTContacts.a to To build Phases of my project i get this Error on build: "linker command failed with exit code 1"

can someone help me?

<img width="1023" alt="Screenshot 2020-10-30 at 07 15 23" src="https://user-images.githubusercontent.com/38873437/97693287-b7b20c80-1a7f-11eb-8955-1e1a6644469e.png">

**Comment by joaonew** [comment]
I have the same error with:

"react": "16.8.3",
"react-native": "0.59.9",
"react-native-contacts": "4.0.2"

I already tried deleting the Library and Framework Paths on Build Settings but couldn't fix this error so far, any ideias?

**Comment by morenoh149** [comment]
looks like react is not found. Did you read the whole readme? https://github.com/morenoh149/react-native-contacts#ios
