### ISSUE TITLE
[Question/Android] does `openContactForm` requries to add the `android.permission.WRITE_CONTACTS` permission?

### ISSUE THREAD

**Issue by oferRounds** [morenoh149/react-native-contacts#576]
It seems to me that no, because we it just open the form for the user (while populating the fields), but the app does not actually perform the writing, but the user

**Comment by morenoh149** [comment]
I think it does need it. If you find it doesn't then feel free to omit it.

**Comment by oferRounds** [comment]
Ok, thanks!
