### ISSUE TITLE
is there a way to detect if a user add contact while the app was running on the background?

### ISSUE THREAD

**Issue by codeamo** [morenoh149/react-native-contacts#580]
I am not sure if this question was asked before but, for convenience reasons is it possible to detect when a user adds a new contact while outside our app? a good example would be a user adds contact while our app is running in the background and then the user right way comes back to our app, looking for the newly created contact to perform some app-specific features.
I am supposed to load contacts every time the user navigates between apps? if this feature is not available, it would be amazing to consider adding as a feature. Thanks

**Comment by morenoh149** [comment]
this library cannot do that.
