### ISSUE TITLE
on Android versions 7.0 whole name properties are not working.

### ISSUE THREAD

**Issue by on29-dev** [morenoh149/react-native-contacts#581]
== English ==
As you give example contact record on document, I tried to set user information to phone contacts app from app(rn). But All of your name examples (familyName, givenName, middleName) are not working correctly. The phone contacts app shows me a blank input(every input about name). 

ThumbnailPath is also not working.
Below is my example.
```javascript
const person = {
  emailAddresses: [
    {
      label: "work",
      email: "abc@abc.com",
    },
  ],
  givenName: "Carl",
  familyName: "Jung",
  middleName: "von",
  phoneNumbers: [
    {
      label: "work",
      number: "123-456-7890",
    },
    {
      label: "mobile",
      number: "123-456-7890",
    },
  ],
  company: "company",
  jobTitle: "jobTitle",
  postalAddresses: [
  ],
  hasThumbnail: true,
  thumbnailPath: "https://.../userImgae.jpg",
}
```

Except for them, the rest are working well.
My test environment is Android version 7.0(galaxy s6 edge)

Please give me an answer about the issue.

== Korean ==

문서에 제시된 예시대로 유저 정보를 세팅하여 기기 연락처 앱으로 정보를 보냈으나, 모든 이름영역(성, 이름, 중간이름) 모두 정상작동하지 않습니다. 기기 연락처 앱의 모든 이름 영역은 빈 칸으로 나옵니다.

ThumbnailPath 도 정상작동하지 않습니다.
아래 예시가 있습니다.
(영문 예시로 갈음)

그것들을 빼고서 나머지는 모두 잘 작동합니다.
제 테스트 환경은 안드로이드 7.0(갤럭시 s6 엣지)입니다.

답변 부탁드립니다.

**Comment by morenoh149** [comment]
sounds like a bug. Please fix and submit a PR.
