### ISSUE TITLE
Can't Save or Retrieve Prefix or Suffix on iOS

### ISSUE THREAD

**Issue by cvharris** [morenoh149/react-native-contacts#582]
I'm running `react-native-contacts@5.2.0` on iOS 14.2 and calling, for example, either `updateContact()` or `getAll()` does not save or get `prefix` or `suffix`.

Tried seeing if a recent update fixed it, so upgraded to `6.0.3` and still broken. Tried on an older iOS version **12.2** to see if it was part of the updates in iOS contacts and wasn't working either.

**Comment by jacstrong** [comment]
I'm currently having this same issue. Using `react-native-contacts@7.0.5` and `getAll()` does not return prefix or suffix on contacts that have them.

```.js
// results from Contacts.getAll()
[
  otherResults,
  {
    "company": "",
    "emailAddresses": [],
    "familyName": "",
    "givenName": "FirstName",
    "hasThumbnail": true,
    "imAddresses": [],
    "jobTitle": "",
    "middleName": "",
    "phoneNumbers": [],
    "postalAddresses": [],
    "recordID": "25A5D381-E893-445F-9A5C-BD97314ED1B9:ABPerson",
    "thumbnailPath": "...",
    "urlAddresses": []
  }
]
```

![Simulator Screen Shot - iPhone 14 - 2023-01-31 at 20 43 15](https://user-images.githubusercontent.com/25963322/215953942-65e808db-e837-43f3-9f33-c9914a38cec0.png)

**Comment by morenoh149** [comment]
prefix, suffix aren't part of the api exposed. The api for contact shape is at https://github.com/morenoh149/react-native-contacts#example-contact-record the first step to returning these fields is to confirm that android store this info as well?

Depending on what android stores we can update the api to return this information.
