### ISSUE TITLE
Android error: Contacts.getAll got 3 arguments, expected 2

### ISSUE THREAD

**Issue by yahorbukhta** [morenoh149/react-native-contacts#583]
Version: 6.0.3

Code: 
```
return PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.READ_CONTACTS,
      {
        'title': 'Contacts',
        'message': 'This app would like to view your contacts.',
        'buttonPositive': 'Allow'
      }
    )
      .then(Contacts.getAll);
```

Error on running
` com.facebook.react.bridge.NativeArgumentsParseException: Contacts.getAll got 3 arguments, expected 2`

<img width="400" alt="image" src="https://user-images.githubusercontent.com/65916399/103289825-33392700-49f9-11eb-9157-1584aa55d897.png">

**Comment by morenoh149** [comment]
does the example throw the same error? https://github.com/morenoh149/react-native-contacts/tree/master/example

**Comment by Biciato** [comment]
> does the example throw the same error? https://github.com/morenoh149/react-native-contacts/tree/master/example

which example ?

**Comment by Biciato** [comment]
> Version: 6.0.3
> 
> Code:
> 
> ```
> return PermissionsAndroid.request(
>       PermissionsAndroid.PERMISSIONS.READ_CONTACTS,
>       {
>         'title': 'Contacts',
>         'message': 'This app would like to view your contacts.',
>         'buttonPositive': 'Allow'
>       }
>     )
>       .then(Contacts.getAll);
> ```
> 
> Error on running
> ` com.facebook.react.bridge.NativeArgumentsParseException: Contacts.getAll got 3 arguments, expected 2`
> 
> <img alt="image" width="400" src="https://user-images.githubusercontent.com/65916399/103289825-33392700-49f9-11eb-9157-1584aa55d897.png">

change .then(Contacts.getAll); by .then(() => Contacts.getAll()); solves for me

**Comment by morenoh149** [comment]
very odd, feels like `getAll` is getting 3 args but it only needs 2. Shouldn't javascript ignore the third arg? maybe its the native bridge that can't ignore the third arg.

**Comment by Biciato** [comment]
> very odd, feels like `getAll` is getting 3 args but it only needs 2. Shouldn't javascript ignore the third arg? maybe its the native bridge that can't ignore the third arg.

It's the Java part that complains, not javascript

**Comment by SalvaHasan** [comment]
The following changes fixed this issue for me, write await before the Contacts.getAll and change this to: 
`Contacts.getAll` 
to 
`await Contact.getAll()`

**Comment by morenoh149** [comment]
@SalvaHasan that looks right. The current api is async.

**Comment by ibelgin** [comment]
> .then(() => Contacts.getAll());

I tried this but my app closes when i run that

**Comment by morenoh149** [comment]
@ibelgin need more code. Did you try?
```
.then(async () => {
  await Contacts.getAll();
 });
```
