### ISSUE TITLE
Android imported contact does not have notes

### ISSUE THREAD

**Issue by rdewolff** [morenoh149/react-native-contacts#585]
When importing contact from Android phone, the info are passed, but the note are empty.

Tested on versions : 5.2.0 and 6.0.3. 

Related PR and issues:
- https://github.com/morenoh149/react-native-contacts/pull/512 (not merged, any info @morenoh149 ?)
- https://github.com/morenoh149/react-native-contacts/issues/406 (no reply? auto closed by bot)

**Comment by morenoh149** [comment]
thanks for digging in. #512 never got a follow up from the author. If you test and confirm it works I'd be happy to cut a release with it.

**Comment by AleksDominik** [comment]
same here.

**Comment by morenoh149** [comment]
@AleksDominik please review #512

**Comment by rdewolff** [comment]
The PR in #512 does work and fixes the issue.
