### ISSUE TITLE
Blank contacts have null as displayName, givenName and suffix

### ISSUE THREAD

**Issue by mark-karrica** [morenoh149/react-native-contacts#588]
I found 4 blank contacts (and I don't know how they got there). They have displayName, givenName, prefix and suffix saved as null (which is not written in the typescript definitions). This can be easily fixed by adding the possible null type in the typescript definitions or by setting an empty string by default.
![Blank contact](https://user-images.githubusercontent.com/60916242/106380774-b103a000-63b4-11eb-8381-6155678a2df7.png)

**Comment by morenoh149** [comment]
feel free to add to https://github.com/morenoh149/react-native-contacts/blob/master/index.d.ts

**Comment by Cutsman24** [comment]
Please disregard, post made in error.
