### ISSUE TITLE
React native contact crush my application

### ISSUE THREAD

**Issue by Drabo416** [morenoh149/react-native-contacts#589]
good evening dear developers, I want to use react native contact to access my contacts but my application crashes on startup. when i remove i getContacts code the application chews. I need your help, I am working on a project and I have a deadline to meet

**Comment by JonathasLopes** [comment]
good morning! The same problem here...

**Comment by oxyii** [comment]
Same here. downgrade to `< v6` helps for me. In my case works fine on `v5.2.8`

**Comment by oxyii** [comment]
I understand my problem. Starting v6 api was changed from callback as arg to Promise-like... it's hard to find such a minor change in a code the size of New York.

@morenoh149 it would be great to check for the presence of method arguments and issue a warning if any. At least in the first versions after api changes. I lost a day looking for this error :(

**Comment by morenoh149** [comment]
@oxyii readme says it returns a promise right there https://github.com/morenoh149/react-native-contacts#api

if you want to improve the docs or example submit a PR

**Comment by morenoh149** [comment]
closing for ambiguous.
