### ISSUE TITLE
App crashing for android for react native contacts

### ISSUE THREAD

**Issue by TayyabNaveed** [morenoh149/react-native-contacts#590]
i followed all the steps for android, according to the docs i had to add
```
@Override
protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new ReactNativeContacts()); // <------ add this 
  }
```
But this gave an error while building that this  method does not override or implement a method from a supertype, i removed the @override keyword and the app is building but crashes on startup. I added the permission in manifest too. 
I have very little android background. Any help would be appreciated!

p.s i also had to import 
import java.util.List;
import java.util.Arrays;
to make this work.

**Comment by oxyii** [comment]
+1
@TayyabNaveed downgrade to `< v6` helps for me. In my case works fine on `v5.2.8`
