### ISSUE TITLE
Malformed calls from JS: field sizes are different.

### ISSUE THREAD

**Issue by aman-singh-unthinkable** [morenoh149/react-native-contacts#607]
![Simulator Screen Shot - iPhone 11 - 2021-04-01 at 13 27 45](https://user-images.githubusercontent.com/74185365/113262548-5cb26900-92ee-11eb-9c81-13277dac9939.png)
Issue in iOS only

code 👇
<img width="884" alt="Screenshot 2021-04-01 at 1 39 10 PM" src="https://user-images.githubusercontent.com/74185365/113263754-cda65080-92ef-11eb-89a2-3bcd1e30e082.png">

**Comment by muhammada86** [comment]
Contacts.getAll()
    .then((contacts) => {
      // work with contacts
    })
    .catch((e) => { //handle error })
    
    use this code after version 6 ... 
    
    found answer from stackoverflow 
    https://stackoverflow.com/questions/65222168/malformed-calls-from-js-field-sizes-are-different-8-39-4-0
