### ISSUE TITLE
Crash when READ_CONTACTS permissions is not asked

### ISSUE THREAD

**Issue by OlivierVoyer** [morenoh149/react-native-contacts#609]
When using Contacts.openContactForm in Android, the app is crashing when saving the contact if we don't have READ_CONTACTS permission.

    "react-native": "0.64.0",
    "react-native-contacts": "^7.0.0",

That would be great being able to use the package only to write new contacts and then not asking this specific permission, thus not needing an App Privacy setup in Google Play.

Thanks in advance

**Comment by morenoh149** [comment]
I don't think it's an issue. If you want to change the docs or the way the software works submit a PR.
