### ISSUE TITLE
openExistingContact in view mode

### ISSUE THREAD

**Issue by AndreaGProg** [morenoh149/react-native-contacts#612]
Hi!

The "openExistingContact" method opens the contact in edit mode (see the first screenshot).

How can I open the contact in view mode? (see the second screenshot).

The third screenshot shows how the contact is displayed with the "editExistingContact" function.
 

**1) openExistingContact - this is in edit mode**

<img width="248" alt="1_openExistingContact" src="https://user-images.githubusercontent.com/60134321/115251528-eeadd480-a12a-11eb-8920-489a44857c8d.png">

**2) open contact with Contacts App - I would like this**

<img width="243" alt="2_from_app_contacts" src="https://user-images.githubusercontent.com/60134321/115251536-efdf0180-a12a-11eb-8676-859403de50cb.png">

**3) editExistingContact**

<img width="253" alt="3_editExistingContact" src="https://user-images.githubusercontent.com/60134321/115252835-1baeb700-a12c-11eb-8fbf-d6322e895d94.png">

**Comment by morenoh149** [comment]
you can't at the moment.
