### ISSUE TITLE
empty list if contacts more than 400

### ISSUE THREAD

**Issue by saratpatti** [morenoh149/react-native-contacts#614]
I am getting empty list if contacts in my phone book are greater than say 400.

Last I tested for 302 contacts, list was visible fine but for larger list of contacts app is unable to display contacts.

**Comment by saratpatti** [comment]
Hello, @morenoh149 let me know the steps to reproduce it or can you test it with yourself ?

I am using version 5.2.3 otherwise if I use the latest version of the library it gives malformed calls from js error.

Any idea how to solve this?

**Comment by morenoh149** [comment]
the latest version returns a promise, which is why you see that error.

We need another engineer to reproduce the issue. I don't have the time to reproduce it myself.

**Comment by saratpatti** [comment]
> the latest version returns a promise, which is why you see that error.
> 
> We need another engineer to reproduce the issue. I don't have the time to reproduce it myself.

Can you share sample code here how we can rectify the issue with latest version

**Comment by morenoh149** [comment]
@saratpatti I don't know how to fix your issue. If you follow the readme and read the example project you'll see how to use the software

https://github.com/morenoh149/react-native-contacts/blob/master/example/App.js#L64

**Comment by micha1333** [comment]
Hello Everyone,
I am getting an empty list if contacts are greater than 500. 
I have tested on multiple devices.
first phone has 200 people, this package works well.
second phone has 300 people, this package works well.
other devices have 450, 1000 peoples, this package gives an empty list.
I am sure that it does not work well if there is over 400 people in phone contacts.
Please help me.

Best regards,
Mikhailo
