### ISSUE TITLE
Add  base64 thumbnail path using openContactForm

### ISSUE THREAD

**Issue by daniel-moya** [morenoh149/react-native-contacts#618]
When using `Contacts.openContactForm()`, is it possible to use an base64 image uri ? 

For example 
``` javascript
Contacts.openContactForm({
	hasThumbnail: true,
	thumbnailPath: contact?.base64image,
});
```

Since I have seen this Issue #470,, I'm not sure if the feature is available now

>I want to create a new contact with thumbnail image.

Reply: 

>This library cannot do that

**Comment by morenoh149** [comment]
not possible right now. Additions welcome.
