### ISSUE TITLE
GetAll on Android not returning if we have a lot of contacts.

### ISSUE THREAD

**Issue by CodeXpertsDev** [morenoh149/react-native-contacts#626]
I am using react-native-contacts library in one of my app, and we are having an issue where getAll contacts method is not returning at all if device has a lot of contacts. 
In our case tester has over 4000 contacts (yes he is very popular :p)

**Comment by CodeXpertsDev** [comment]
@morenoh149 Any help we can get here.

**Comment by morenoh149** [comment]
@CodeXpertsDev the api needs to support pagination (like most web apis). See https://github.com/morenoh149/react-native-contacts/issues/226
