### ISSUE TITLE
how to mock react-native-contacts with jest

### ISSUE THREAD

**Issue by dsagredo** [morenoh149/react-native-contacts#632]
Any solutions or advice on how to mock both components with Jest, and not just one? I am very new to Jest.

**Comment by morenoh149** [comment]
nope, that is a jest question.

**Comment by rajAmukhliS** [comment]
mock r`eact-native-contacts` inside test file 

```
jest.mock('react-native-contacts', () => ({
  checkPermission: jest
    .fn()
    .mockImplementation(() => Promise.resolve('undefined')),
  getAll: jest.fn().mockImplementation(() => Promise.resolve([])),
  requestPermission: jest
    .fn()
    .mockImplementation(() => Promise.resolve('undefined')),
  getContactsMatchingString: jest
    .fn()
    .mockImplementation(() => Promise.resolve([])),
}));
```

and mock `react-native-permissions `also in `jest.setup.js` or on top of test file

j```
est.mock('react-native-permissions', () =>
  require('react-native-permissions/mock'),
);
```
