### ISSUE TITLE
Listen to Contact Store Updates

### ISSUE THREAD

**Issue by jbromberg** [morenoh149/react-native-contacts#637]
Apple provides an API for knowing when a user's contacts have changed. It is called CNContactStoreDidChange.

Documentation: https://developer.apple.com/documentation/foundation/nsnotification/name/1403253-cncontactstoredidchange

It is extremely common for apps to periodically sync a user's contacts with the server and this would make that very easy. Right now, the only solution with this library is to periodically fetch the user's entire contact list and see what has been changed. Implementing this API would be extremely helpful to many people using this library. I would be willing to do it, but unfortunately, I don't know any native code.

**Comment by mfbx9da4** [comment]
I believe Android also provides this functionality through sync adapters. Is there any reason why it's not possible to unify their APIs?

https://developer.android.com/guide/topics/providers/contacts-provider#Sources
