### ISSUE TITLE
I am facing  "Possible Unhandled Promise Rejection (id: 0): " while calling Contacts.getAll() in android.

### ISSUE THREAD

**Issue by chetan-sharma-newput** [morenoh149/react-native-contacts#638]
Hello there, 
I am facing  Possible Unhandled Promise Rejection (id: 0): TypeError: Cannot convert undefined value to object TypeError: Cannot convert undefined value to object while calling Contacts.getAll() from android device.

`const userContacts = await Contacts.getAll()`
This is how I am calling the method. I tried .then.catch also but no luck. it's urgent.

Note:- I am not facing this issue when I start debugging the app. But when I stop debugging and create a sign-in build of the app then I face this issue.

<img width="996" alt="Screenshot 2021-09-06 at 9 26 13 PM" src="https://user-images.githubusercontent.com/59158878/132242266-2c525b81-8574-4c05-8cba-f5dd87f83ace.png">

**Comment by vincentzierigen** [comment]
Having the same issue

**Comment by chetan-sharma-newput** [comment]
> Having the same issue

Hello, after that issue I debug my code. In the code, I was replacing some strings and calling string.replaceAll() method but later i found there is no method in react-native called replaceAll(). RN only provide replace() method. Thanks.
