### ISSUE TITLE
Month inconsistencies between iOS and Android

### ISSUE THREAD

**Issue by ejoncas-rivalbet** [morenoh149/react-native-contacts#641]
iOS substracts -1 to the month to make it zero-indexed.

https://github.com/morenoh149/react-native-contacts/blob/master/ios/RCTContacts/RCTContacts.m#L346

But then Android does not
https://github.com/morenoh149/react-native-contacts/blob/master/android/src/main/java/com/rt2zz/reactnativecontacts/ContactsProvider.java#L541

I think we should make it consistent. My preference is to keep 1-indexed months to keep it consistent with day and year fields.

**Comment by morenoh149** [comment]
still a good first issue.
