### ISSUE TITLE
Execution failed for task ':react-native-unified-contacts:compileDebugJavaWithJa vac'.

### ISSUE THREAD

**Issue by shehan-bro** [morenoh149/react-native-contacts#646]
This is my console output:
:react-native-unified-contacts:compileDebugJavaWithJavac FAILED
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:14: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:15: error: cannot find symbol
import android.support.v4.app.ActivityCompat;
                             ^
  symbol:   class ActivityCompat
  location: package android.support.v4.app
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:16: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:317: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNUnifiedContactsModule
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:355: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNUnifiedContactsModule
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:394: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNUnifiedContactsModule
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:444: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNUnifiedContactsModule
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:480: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNUnifiedContactsModule
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:515: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNUnifiedContactsModule
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:98: error: cannot find symbol
        int userCanAccessContacts = ContextCompat.checkSelfPermission( getCurrentActivity(), Manifest.permission.READ_CONTACTS );
                                    ^
  symbol:   variable ContextCompat
  location: class RNUnifiedContactsModule
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:114: error: cannot find symbol
        boolean canAccessContacts = ContextCompat.checkSelfPermission( getCurrentActivity(), Manifest.permission.READ_CONTACTS ) == PackageManager.PERMISSION_GRANTED;
                                    ^
  symbol:   variable ContextCompat
  location: class RNUnifiedContactsModule
C:\d drive\sendroidProject\node_modules\react-native-unified-contacts\android\src\main\java\com\joshuapinter\RNUnifiedContacts\RNUnifiedContactsModule.java:122: error: cannot find symbol
            ActivityCompat.requestPermissions( getCurrentActivity(), new String[]{ Manifest.permission.READ_CONTACTS }, ON_REQUEST_PERMISSIONS_RESULT_READ_CONTACTS );
            ^
  symbol:   variable ActivityCompat
  location: class RNUnifiedContactsModule
12 errors

**Comment by morenoh149** [comment]
This is your console output when doing what?
