### ISSUE TITLE
Contacts reading issue in Android " Malformed calls from JS: field sizes are different ..."  due to incorrect syntax mentioned in READme.md

### ISSUE THREAD

**Issue by sreerajmp** [morenoh149/react-native-contacts#647]
Read me contains incorrect syntax getall contacts.
ie:
```es
import` { PermissionsAndroid } from 'react-native';
import Contacts from 'react-native-contacts';

PermissionsAndroid.request(
  PermissionsAndroid.PERMISSIONS.READ_CONTACTS,
  {
    'title': 'Contacts',
    'message': 'This app would like to view your contacts.',
    'buttonPositive': 'Please accept bare mortal'
  }
)
.then(Contacts.getAll)
.then(contacts => {
  ...
})
```
This causes the following error in android:
![WhatsApp Image 2021-11-19 at 2 36 16 AM](https://user-images.githubusercontent.com/46236991/142501620-447dbb4b-a363-4849-952a-24ba974b43e3.jpeg)

**Comment by gsietsetb** [comment]
I had the exact same issue and needed to downgrade to : 
`        "react-native-contacts": "5.0.2",`

**Comment by morenoh149** [comment]
the latest api uses promises. Please use the latest apis.
