### ISSUE TITLE
App is crashing on getCount and getAll

### ISSUE THREAD

**Issue by asalha** [morenoh149/react-native-contacts#655]
Hello,

I followed exactly the same requirements as mentioned in the README file. When I check the permission status it's "granted" then I run `Contacts.getCount()` or `Contacts.getAll()` the app crashes on Android (simulator and real device).

Any idea?

**Comment by kruz123** [comment]
Hello,

**@asalha** please share your code because recently i used this library and its working fine.
so please share your code with for better understanding what you faced your problem and trying to solve your problem.

Thanks.

**Comment by asalha** [comment]
> Hello,
> 
> **@asalha** please share your code because recently i used this library and its working fine.
> so please share your code with for better understanding what you faced your problem and trying to solve your problem.
> 
> Thanks.

Sorry, I'm not using it anymore, I've replaced it with expo-contacts

**Comment by kruz123** [comment]
ok no issue

**Comment by ZaharGusyatin** [comment]
any updates?

**Comment by sheggietyn** [comment]
same here the App keep crashing/ closing when i try to display all contact

**Comment by kruz123** [comment]
Hello,

@sheggietyn please share your code .
Thanks.

**Comment by hocraveiro** [comment]
I had the same problem recently, it was because I didn't declare the contact permission at AndroidManifest.xml

<uses-permission android:name="android.permission.READ_CONTACTS" />

Just add this line in your AndroidManifest.xml and run npx react-native run-android again

**Comment by kruz123** [comment]
hello @hocraveiro 
his issue is that when he shows all his contacts, then his app crashes.
not like your issue

**Comment by biplovappservinc** [comment]
@hocraveiro 
same here

**Comment by biplovappservinc** [comment]
@asalha 

just add permission in Info.plist

```
	<key>NSContactsUsageDescription</key>
	<string>Contact Permission</string>
```

then it will be solved

**Comment by mortocks** [comment]
Features work for me, suspect you've forgotten to add permissions to android or iOS info.plist as @biplovappservinc suggests

**Comment by rajAmukhliS** [comment]
This is because in android ### you didn't allow permission of READ_CONTACTS.

To get rid of this crash you have to write **READ_CONTACTS** permission inside `AndroidManifest.xml `

Write the below permission inside `android/app/src/AndroidManifest.xml `

```
...
<uses-permission android:name="android.permission.READ_CONTACTS" />
...
```
