### ISSUE TITLE
null is not an object (evaluating '_reactNativeContacts.Contacts')

### ISSUE THREAD

**Issue by pycode7** [morenoh149/react-native-contacts#664]
Is any problem with the expo? because I have the same problem react-native-contacts don't work properly.

**Comment by Shubham567** [comment]
same

**Comment by brianbit9** [comment]
same

**Comment by shikhardixitprojects** [comment]
@pycode7 @Shubham567 @brianbit9 
I was facing the same issue. Make sure you add the following properly in your Info.plist

<img width="748" alt="Screenshot 2024-01-17 at 6 59 15 PM" src="https://github.com/morenoh149/react-native-contacts/assets/45184269/5740695e-eab2-4917-8880-6cf19d1a8069">

And then the most important thing is re-build from Xcode. Changes to Info.plist are not acknowledged until you re-build :D
