### ISSUE TITLE
Update contact thumbnail 

### ISSUE THREAD

**Issue by mustapha-ghlissi** [morenoh149/react-native-contacts#667]
HI community !

I'm working on a custom contacts app where I have a form to set some infos and take a photo using the camera, 
But when trying to save the infos, only thumbnail isn't saved !!!!

Anyone can help me ? 

Here is my code to take a picture via camera and set the contact infos:

```
ImagePicker.openCamera({
      width: 200,
      height: 200,
      cropping: false
    }).then(({path}) => {
      setContactObj({
        ...contactObj,
        thumbnailPath: path,
        hasThumbnail: true
      });
    });
    
    
    Contacts.updateContact(contactObj).then(() => {
      Alert.alert('Success', 'Contact infos updated successfully !');
    })
```

**Comment by adenta** [comment]
@mustapha-ghlissi were you able to figure this out? Is this even possible? @morenoh149

**Comment by morenoh149** [comment]
@adenta not sure I've never used the thumbnails
