### ISSUE TITLE
Could not resolve project :react-native-contacts.

### ISSUE THREAD

**Issue by sumitapporio** [morenoh149/react-native-contacts#674]
1. npm install
2. compiling app from android studio.

Could not determine the dependencies of task ':app:compileEkshotCustomerDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:ekshotCustomerDebugCompileClasspath'.
   > Could not resolve project :react-native-contacts.
     Required by:
         project :app
      > No matching configuration of project :react-native-contacts was found. The consumer was configured to find an API of a component, as well as attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'debug', attribute 'ekshotCustomer' with value 'ekshotCustomer' but:
          - None of the consumable configurations have attributes.

**Comment by sumitapporio** [comment]
Any solution?

**Comment by morenoh149** [comment]
Did you try rebuilding from source and removing any outdated dependencies?
