### ISSUE TITLE
App crashes immediately on android

### ISSUE THREAD

**Issue by akanz** [morenoh149/react-native-contacts#684]
Good day guys, RN contacts works fine on ios but crashes immediately I try to access the contacts on android. I configured permissions in manifest file and also req permission when accessing.

<img width="1001" alt="Screenshot 2022-08-09 at 17 27 58" src="https://user-images.githubusercontent.com/33222698/183706919-6b486506-81ae-452a-a097-da1374858621.png">

**Comment by prox2** [comment]
Having same issue
