### ISSUE TITLE
Empty birthday field in creating new contact IOS 

### ISSUE THREAD

**Issue by wfrsnk** [morenoh149/react-native-contacts#686]
In IOS 12.4 if i want to add a new contact, the contact form behaves strangely:
birthday field is empty, but i set it in sending object like "birthday: { day: '12', month: '07' }";
if i tap to empty field, the application freezes until reboot it;
if i ignore empty field and save contact, it saves and in phone contacts this one has correct birthday date.

In IOS 15.4 it works correct.

**Comment by morenoh149** [comment]
we aren't trying to support older versions of operating systems.

**Comment by wfrsnk** [comment]
In my solution, versions IOS older, then 13.0 needs "year" key for correctly display at form and fix it. But this key breaks a form in versions after 13.0
