### ISSUE TITLE
Unsaved Draft with openContactForm open when open default phone app (iOS)

### ISSUE THREAD

**Issue by kukadiyaAni** [morenoh149/react-native-contacts#692]
Platform: iOS
Step to reproduce the issue

1. Open the app and execute the below code

```
const newPerson = {
      phoneNumbers: [
        {
          label: "mobile",
          number: 9876543210,
        },
      ],
    };

Contacts.openContactForm(newPerson).then(contact => {
  // contact has been saved
})
```

2. Open a new contact modal
![simulator_screenshot_BCFF8301-1C9F-43CE-A05E-80C0E72AA7CF](https://user-images.githubusercontent.com/16218216/190608813-0955c7aa-6b34-4ad2-9ec3-187a116a4794.png)

3. Click on Cancel and select `Discard Changes`

4. Now close app and open default iOS Phone app and automatically open Unsave draft with the above number

**Comment by morenoh149** [comment]
is it saving the draft or not? One could argue that either behavior is correct.

**Comment by kukadiyaAni** [comment]
@morenoh149 it's saving on draft and when open default Phone app then open this modal with old detail while I discard changes from my app

**Comment by kukadiyaAni** [comment]
@morenoh149 did you find solution for that?

**Comment by kukadiyaAni** [comment]
I'm react native developer with base Android developer not much experience in iOS, if any help me here to remove draft so, I can update in iOS

**Comment by kukadiyaAni** [comment]
this issue still there please any one suggest me solution
