### ISSUE TITLE
build failed after installing

### ISSUE THREAD

**Issue by kingofday** [morenoh149/react-native-contacts#695]
i have a  rn project with these config:
"react-native": "0.68.1",
"react-native-contacts": "^7.0.5",
buildToolsVersion = "31.0.0"
minSdkVersion = 21
compileSdkVersion = 31
targetSdkVersion = 31
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip
        
so i installed react-native-contacts and because its autolink, there is no extra installation steps if guess right, after build for android i cant download gradle 4.1.0 and it gives this error!
```
    Could not resolve all files for configuration ':react-native-contacts:classpath'.
   > Could not find gradle-4.1.0.jar (com.android.tools.build:gradle:4.1.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/4.1.0/gradle-4.1.0.jar
```
please help, why is that! i tried to build with vpn or proxy but it didnt worked

**Comment by morenoh149** [comment]
try adding

```
maven { url "https://maven.google.com" }
```

to https://github.com/morenoh149/react-native-contacts/blob/master/android/build.gradle#L2

https://stackoverflow.com/a/66584470/630752
