### ISSUE TITLE
iOS unable to access Prefix & suffix among other fields.

### ISSUE THREAD

**Issue by jacstrong** [morenoh149/react-native-contacts#703]
I'm currently having this same issue. Using `react-native-contacts@7.0.5` and `getAll()` does not return prefix or suffix on contacts that have them.

```.js
// results from Contacts.getAll()
[
  otherResults,
  {
    "company": "",
    "emailAddresses": [],
    "familyName": "",
    "givenName": "FirstName",
    "hasThumbnail": true,
    "imAddresses": [],
    "jobTitle": "",
    "middleName": "",
    "phoneNumbers": [],
    "postalAddresses": [],
    "recordID": "25A5D381-E893-445F-9A5C-BD97314ED1B9:ABPerson",
    "thumbnailPath": "...",
    "urlAddresses": []
  }
]
```

![Simulator Screen Shot - iPhone 14 - 2023-01-31 at 20 43 15](https://user-images.githubusercontent.com/25963322/215953942-65e808db-e837-43f3-9f33-c9914a38cec0.png)

**Comment by morenoh149** [comment]
Does android store prefix?
