### ISSUE TITLE
How to get or fetch real time contacts in react native

### ISSUE THREAD

**Issue by pankajvrinsoft** [morenoh149/react-native-contacts#708]
Anyone knows how to get or fetch real time contacts in react native. I used latest version of react-native-contacts library. first of all i'm getting my all contacts in app. but suppose if i change any contacts name in my phone then it should be updated in my app as well. right now it is not update the name.

already tried the permissions of read and write contacts and profile permission as well. and good thing is it is working well in iOS and android older versions. issue came in new android versions like android version 11,12 and 13.

**Comment by MatanB-Inmanage** [comment]
Same here. I need help!
