### ISSUE TITLE
Show Permission Dialog when checking permission.

### ISSUE THREAD

**Issue by airakivela** [morenoh149/react-native-contacts#709]
I am trying to show custom screen before show contact permission dialog on Android.
When I check this permission is granted or not, contact permission dialog show eventhough I did not call contact permission request.
iOS is working fine.. AndroidPermissions package is sending request when I check permission??
Hope your assist.
Thanks.

**Comment by morenoh149** [comment]
We might have to make the permissions requesting more granular. Right now we request all permissions regardless if you are actually going to need it. Because our api covers those permissions.

PRs welcome to change the api to make permissions asking more granular.
