### ISSUE TITLE
getContactsByPhoneNumber only returns after match

### ISSUE THREAD

**Issue by HeatherHaylett** [morenoh149/react-native-contacts#711]
`getContactsByPhoneNumber` will only return a contact once the full number creates a match in contacts. I'd like to be able to search string by string.

For example
Instead of only match `555-555-5555`, show all contacts matching `5` then narrowing down as each number is added.

**Comment by digholesnehal** [comment]
@morenoh149  I would like to work on this issue as a contributor. Could you please assign it to me?

Regards,
Snehal

**Comment by morenoh149** [comment]
@digholesnehal assigned

**Comment by morenoh149** [comment]
@digholesnehal any update?

**Comment by digholesnehal** [comment]
Hey @morenoh149, I'm sorry but I was unable to run the code for development and testing and hence could not proceed. I need some guidance on how to start.

**Comment by morenoh149** [comment]
@digholesnehal what help do you need specifically? did you try cloning the code first

the next step is to use the cloned code locally in an example app, so you can test changes locally before sharing them into the main project

**Comment by digholesnehal** [comment]
@morenoh149 , sorry for not being specific. But I already followed all the above stated stages, and faced issue while running "npm run android" script to run example app code.

Please find the attached screenshot here,
![image](https://github.com/morenoh149/react-native-contacts/assets/41193359/a1ae6e33-4732-4c3f-a8c3-5612b0dc8fec)

I tried to solve the same as well, but got no luck.
Thank you for your responses.
