### ISSUE TITLE
iOS: UIColor created with component values far outside the expected range

### ISSUE THREAD

**Issue by jwoodmansey** [morenoh149/react-native-contacts#726]
Hi, we seem to be seeing this log in Xcode coming from this library:

```
UIColor created with component values far outside the expected range. Set a breakpoint on UIColorBreakForOutOfRangeColorComponents to debug. This message will only be logged once.
```

I've tried to locate the source looking through the source code but struggling to find it.

**Comment by morenoh149** [comment]
there are two sections with `UIColor` https://github.com/search?q=repo%3Amorenoh149%2Freact-native-contacts%20UIColor&type=code

you are either running the example or running that obj-c code. For the latter it depends on your ios version. This var seems to be a global https://developer.apple.com/documentation/uikit/uicolor/3173138-secondarysystemgroupedbackground

lmk what you think

**Comment by Rajat-verma-99** [comment]
+1
