### ISSUE TITLE
birthday do not work

### ISSUE THREAD

**Issue by theshilovs** [morenoh149/react-native-contacts#728]
Birthday is not created on the device. What am I doing wrong?

  
Android 13,
"react": "18.2.0",
"react-native-contacts": "^7.0.8",

```
const newContactPhone = () => {
    const contact = {
      familyName: 'test',
      givenName: 'test',
      isStarred: true,
      birthday: {day: 30, month: 4, year: 1979},
    };
    Contacts.addContact(contact).then(contact => {
      console.log(contact, 'CONTACTPHONE');
    });
  };
```
 LOG  {"company": null, "department": null, "displayName": "test test", "emailAddresses": [], "familyName": "test", "givenName": "test", "hasThumbnail": false, "imAddresses": [], "isStarred": false, "jobTitle": null, "middleName": "", "note": null, "phoneNumbers": [], "postalAddresses": [], "prefix": null, "rawContactId": "4828", "recordID": "4829", "suffix": null, "thumbnailPath": "", "urlAddresses": []} CONTACTPHONE

**Comment by morenoh149** [comment]
similar deal as https://github.com/morenoh149/react-native-contacts/issues/727

we need to unpack the birthdate and append an EVENT on the contact

https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Event#TYPE_BIRTHDAY
