### ISSUE TITLE
getContactsMatchingString search also in addresses

### ISSUE THREAD

**Issue by dprevost-LMI** [morenoh149/react-native-contacts#729]
In the doc, we can see: 
```
getContactsMatchingString(string): Promise<Contact[]> - where string is any string to match a name (first, middle, family) to
```
This is misleading since the `getContactsMatchingString` also searches inside `postalAddresses`. I did a quick test, and by entering the stress name, I had results that did not fit the name.

Would you mind adjusting the doc so we know explicitly which fields are used for the search for `getContactsMatchingString`?

**Comment by morenoh149** [comment]
@dprevost-LMI feel free to fix the doc and submit a PR.

**Comment by dprevost-LMI** [comment]
Will do soon
