### ISSUE TITLE
Get Call history

### ISSUE THREAD

**Issue by deepakkumardk** [morenoh149/react-native-contacts#730]
I can't find any doc related to getting the call history, I guess this library doesn't support that.
Is there any plan to add this feature, is it in the scope of this library?

**Comment by morenoh149** [comment]
This library does not support that.

**Comment by deepakkumardk** [comment]
Hi @morenoh149 again, is there any plan to add this feature, is it in the scope of this library?
If so I can work on that and create a PR.

**Comment by morenoh149** [comment]
there is no plan to add that feature. But, if call history is something exposed by the underlying apis we would welcome that addition! Please be sure it is something allowed on android and ios.
