### ISSUE TITLE
React Native 0.74 (Bridgeless) Support

### ISSUE THREAD

**Issue by oktaysenkan** [morenoh149/react-native-contacts#736]
Hello,

React Native is transitioning to bridgeless architecture with version 0.74. This architecture aims to improve performance and maintainability by removing the JavaScript bridge, which has traditionally been a bottleneck.

I am currently using your library `react-native-contacts` in my project. It's been incredibly useful, and I appreciate all the effort that goes into maintaining it. With the changes in React Native 0.74, it appears that the library may require updates to ensure full compatibility with the new architecture.

## Links

**[About the New Architecture](https://reactnative.dev/docs/next/the-new-architecture/landing-page)**
**[New Architecture working group](https://github.com/reactwg/react-native-new-architecture)**
**[Library support for New Architecture + Bridgeless in 2024](https://github.com/reactwg/react-native-new-architecture/discussions/167)**
**[Already migrated libs to take as an example](https://reactnative.dev/blog/2022/06/16/resources-migrating-your-react-native-library-to-the-new-architecture#migration-status-of-popular-libraries)**

**Comment by oktaysenkan** [comment]
![Simulator Screenshot - iPhone 15 - 2024-05-06 at 17 58 30](https://github.com/morenoh149/react-native-contacts/assets/42527467/5cf94e51-fe36-40ae-aa3b-ed671bf7c18f)

**Comment by MS0015** [comment]
any update?

**Comment by faljabi** [comment]
Any updates?

**Comment by morenoh149** [comment]
@faljabi no updates. We should probably just merge it and see what happens.

**Comment by morenoh149** [comment]
version 8.0.0 of react-native-contacts has support for the new react native architecture https://www.npmjs.com/package/react-native-contacts
