### ISSUE TITLE
Update types for contact fields that may be null

### ISSUE THREAD

**Issue by thisjeremiah** [morenoh149/react-native-contacts#737]
It seems that `givenName` and `familyName` could be `null` for fetched contacts on Android devices. This possibility is not reflected in the current TS types.

This scenario can be reproduced by creating a contact with no name and only an "important date" (eg birthday) on Android.

If this doesn’t seem like a bug in the implementation, I can make a PR to update the typings for these fields.

**Comment by morenoh149** [comment]
@thisjeremiah please submit a pr updating the typings

**Comment by atheck** [comment]
Hi, thank you for your work! I want to mention that birthday can also be `undefined`. And on Android there is an option to not enter the year of the birthday. Maybe this should then be a `number | null`.

**Comment by morenoh149** [comment]
@atheck sounds right. Feel free to submit a PR.

**Comment by gimi-anders** [comment]
I know this is a closed ticket, but shouldn't the `type.ts` also be updated with this change?
