### ISSUE TITLE
Contact could not be saved when thumbnailPath is invalid on iOS

### ISSUE THREAD

**Issue by ceydaceyhan** [morenoh149/react-native-contacts#738]
I noticed add contact with `addContact` there is no error for save. But user couldn't created on phone contact on iOS. So my example like this:

```es
var newPerson = {
  emailAddresses: ...,
  company: ...,
  givenName: ...,
  familyName: ...,
  jobTitle: ...,
  phoneNumbers: ...,
  hasThumbnail: ...,
  thumbnailPath:
    '/path/to/file/Caches/name.jpg',
}

const res = await Contacts.addContact(newPerson)
```

Res have valid recordID but I don't see the user in contact.

**Comment by morenoh149** [comment]
res is a valid contact id but you dont see the contact? how did you read the contact after adding?
