### ISSUE TITLE
Support for iOS 18 Limited state & contact picker?

### ISSUE THREAD

**Issue by sahil-ahuja-1** [morenoh149/react-native-contacts#744]
Hi @morenoh149 ! Thanks for this awesome and very useful library :) 

I was wondering if you were planning to add support for the upcoming iOS 18 changes with the limited contact state and opening the contact picker?

Right now, the permission shows as authorized even if it is limited. Thanks in advance!

**Comment by morenoh149** [comment]
@sahil-ahuja-1 no plans to support it. Do you have a link to where these features are described?

**Comment by Lee-sungheon** [comment]
@morenoh149 https://developer.apple.com/videos/play/wwdc2024/10121/
Here's a reference to the relevant feature. There is a need for additional functionality regarding limited permissions. Do you still have no plans to add this feature?

**Comment by morenoh149** [comment]
no plans to add it. I'm open to merging the addition if anyone wants to contribute it. The api has to make sense across ios and android.

**Comment by morenoh149** [comment]
@sahil-ahuja-1 v8.0.2 is released, please test it https://www.npmjs.com/package/react-native-contacts
