### ISSUE TITLE
IOS groups

### ISSUE THREAD

**Issue by sergey-shablenko** [morenoh149/react-native-contacts#747]
Hi, there are currently 2 good modules to work with contacts, this one and https://github.com/joshuapinter/react-native-unified-contacts

Is it possible to add groups functionality to this project?
I really like simplicity of this module and ability to display native contact form on IOS
Would be good to add groups support to compensate for lack of isStarred
With groups we could create app specific group to persist favourites, or attempt to parse existing groups to detect default favourites, without it this data will be lost after reinstall

**Comment by mrpmohiburrahman** [comment]
Hi, @morenoh149 ,
I want to work on this issue.

**Comment by mrpmohiburrahman** [comment]
Hi, @morenoh149 , I want to work on this.

**Comment by mrpmohiburrahman** [comment]
@morenoh149 , please, take a look this pr https://github.com/morenoh149/react-native-contacts/pull/763
