### ISSUE TITLE
Assigning to 'id<CNContactViewControllerDelegate> _Nullable' from incompatible type 'RCTContacts - not build error

### ISSUE THREAD

**Issue by ertandk** [morenoh149/react-native-contacts#749]
![Ekran Resmi 2024-09-21 11 47 25](https://github.com/user-attachments/assets/829e0794-c08b-4b9e-a239-d73f641b9cfe)

Hello, I'm trying to run the project after trying all the steps, but I can't get build because of this error. What's the solution? I've been spending a few hours on this problem.

Thank you.

"dependencies": {
    "@adrianso/react-native-device-brightness": "^1.2.7",
    "@react-native-async-storage/async-storage": "^2.0.0",
    "@react-native-community/geolocation": "^3.4.0",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "react": "18.3.1",
    "react-native": "0.75.3",
    "react-native-contacts": "^8.0.0",
    "react-native-maps": "^1.18.0",
    "react-native-permissions": "^4.1.5",
    "react-native-safe-area-context": "^4.11.0",
    "react-native-screens": "^3.34.0",
    "react-native-send-direct-sms": "^0.2.0",
    "react-native-sms": "^1.11.0",
    "react-native-sound": "^0.11.2",
    "react-native-torch": "^1.2.0",
    "react-native-volume-manager": "^1.10.0"
  },

**Comment by nhattuan2209** [comment]
downgrade to version 7, it's work for me

**Comment by ertandk** [comment]
> downgrade to version 7, it's work for me

Yes, it worked when I downgraded to version 7.

**Comment by shav95** [comment]
@morenoh149 same problem

**Comment by morenoh149** [comment]
downgrade to v7, we just released v8.0.0 and will patch it soon.
