### ISSUE TITLE
getAll() function pull contacts from gmail

### ISSUE THREAD

**Issue by ChenZrahia** [morenoh149/react-native-contacts#95]
Hello,
I used that on my app but the getAll() function only pull the contacts from gmail and not from phone.
I can see that when no one have phone number, and only got emails.
Any way to make it pull the contacts from the phone book and not from gmail?
Thank you.

LG G3 5.0.1

my code:

``` es
PhoneContacts.getAll((err, contacts) => {
            if (err && err.type === 'permissionDenied') {
                // x.x
            } else {
                contacts = contacts.map((user) => {
                    this.myContacts.push({
                        isOnline: false,
                        phoneNumber: (user.phoneNumbers && user.phoneNumbers[0]) ? user.phoneNumbers[0].number : '',
                        publicInfo: {
                            fullName: user.givenName + ' ' + user.familyName,
                            picture: user.thumbnailPath
                        }
                    });                   
                });
                console.log(this.myContacts);
        }
}
```

**Comment by SagiUziel** [comment]
1+

**Comment by morenoh149** [comment]
I'm pretty sure this plugin returns all contacts it can. There was another report https://github.com/rt2zz/react-native-contacts/issues/96 saying that even contacts spanning different sources are returned. If you could submit a PR though it'd definitely be considered.

**Comment by ankita2110** [comment]
Which plugin or react native library u used over here

**Comment by ankita2110** [comment]
Please help me out 
I am not able to fetch all contacts from my contacts application to my react native android application

**Comment by morenoh149** [comment]
@ankita2110 what about on iOS?

**Comment by ankita2110** [comment]
I am not doing the iOS app and  I am doing android app .
And even I am not having iOS simulator to run.
Please help me out as I can fetch only few contacts not all the contacts.Is there any more permission needed to fetch all the contacts

**Comment by ankita2110** [comment]
import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import PhoneContacts from 'react-native-contacts';
import { PermissionsAndroid } from 'react-native';

export default class App extends Component {
  myContacts=[];
  componentDidMount() {
     
     PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.READ_CONTACTS,
      {
        'title': 'Contacts',
        'message': 'This app would like to view your contacts.'
      }
    ).then(() => {
      PhoneContacts.getAll((err, contacts) => {
        if (err && err.type === 'permissionDenied') {
            // x.x
        } else {
            contacts = contacts.map((user) => {
                this.myContacts.push({
                    isOnline: true,
                    phoneNumber: (user.phoneNumbers && user.phoneNumbers[0]) ? user.phoneNumbers[0].number : '',
                    publicInfo: {
                        fullName: user.givenName + ' ' + user.familyName,
                        picture: user.thumbnailPath
                    }
                }); 
               

            });
            console.log(this.myContacts);
          
         }
  
})

})
      
}
  
  
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}> React Native!</Text>
       
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF'
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5
  }
});

**Comment by ankita2110** [comment]
Please tell me the issue with this code

**Comment by morenoh149** [comment]
What is the error? what phone model and API Level?

**Comment by ankita2110** [comment]
Phone model : Redmi 3S
Android version of phone : Android  6.0
SDK VERSION:26

**Comment by ankita2110** [comment]
Error :
I am not able to retrieve all the contacts from the phone

**Comment by morenoh149** [comment]
what does your manifest file look like? did you follow https://github.com/rt2zz/react-native-contacts/blob/master/README.md#api-23 ?

**Comment by morenoh149** [comment]
Please share a minimal reproducible example. I should be able to see your error on my machine. A GitHub repo is good.

**Comment by ankita2110** [comment]
All my contacts are  stored in mi account Redmi 
But then too I am about see only few contacts even though all my contacts are saved in mi account.I am not understanding what is actual problem  with it.
